// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model_usage.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
)

const sumModelCallUsageByModel = `-- name: SumModelCallUsageByModel :many
SELECT revision.configured_model_id,
       configured_model.name AS configured_model_name,
       revision.provider_model_slug,
       provider_config.id AS model_provider_config_id,
       provider_config.name AS model_provider_config_name,
       count(*)::bigint AS model_calls,
       count(context.provider_reported_cost_usd)::bigint AS model_calls_with_reported_cost,
       coalesce(sum(context.input_tokens_total), 0)::bigint AS input_tokens_total,
       coalesce(sum(context.uncached_input_tokens), 0)::bigint AS uncached_input_tokens,
       coalesce(sum(context.cache_read_input_tokens), 0)::bigint AS cache_read_input_tokens,
       coalesce(sum(context.cache_write_input_tokens), 0)::bigint AS cache_write_input_tokens,
       coalesce(sum(context.output_tokens_total), 0)::bigint AS output_tokens_total,
       coalesce(sum(context.reasoning_output_tokens), 0)::bigint AS reasoning_output_tokens,
       coalesce(sum(context.provider_reported_cost_usd), 0)::text AS provider_reported_cost_usd
FROM model_call_contexts context
JOIN agents agent ON agent.project_id = context.project_id
  AND agent.id = context.agent_id
JOIN configured_model_revisions revision ON revision.org_id = context.org_id
  AND revision.id = context.configured_model_revision_id
JOIN configured_models configured_model ON configured_model.org_id = revision.org_id
  AND configured_model.id = revision.configured_model_id
JOIN model_provider_configs provider_config ON provider_config.org_id = revision.org_id
  AND provider_config.id = revision.model_provider_config_id
WHERE context.org_id = $1
  AND ($2::uuid IS NULL OR context.project_id = $2::uuid)
  AND (
    $3::uuid IS NULL
    OR (agent.agent_profile_id = $3::uuid AND agent.parent_agent_id IS NULL)
  )
  AND ($4::uuid[] IS NULL OR context.agent_id = ANY($4::uuid[]))
  AND (
    context.input_tokens_total IS NOT NULL
    OR context.output_tokens_total IS NOT NULL
    OR context.provider_reported_cost_usd IS NOT NULL
  )
GROUP BY revision.configured_model_id, configured_model.name, revision.provider_model_slug,
         provider_config.id, provider_config.name
ORDER BY provider_config.name, configured_model.name, revision.provider_model_slug
`

type SumModelCallUsageByModelParams struct {
	OrgID          uuid.UUID
	ProjectID      *uuid.UUID
	AgentProfileID *uuid.UUID
	AgentIds       []uuid.UUID
}

type SumModelCallUsageByModelRow struct {
	ConfiguredModelID          uuid.UUID
	ConfiguredModelName        string
	ProviderModelSlug          string
	ModelProviderConfigID      uuid.UUID
	ModelProviderConfigName    string
	ModelCalls                 int64
	ModelCallsWithReportedCost int64
	InputTokensTotal           int64
	UncachedInputTokens        int64
	CacheReadInputTokens       int64
	CacheWriteInputTokens      int64
	OutputTokensTotal          int64
	ReasoningOutputTokens      int64
	ProviderReportedCostUsd    string
}

// @sqlc-vet-disable model-provider-configs-deleted-at configured-models-deleted-at
// Usage must still resolve when the configured model or provider config is soft deleted.
func (q *Queries) SumModelCallUsageByModel(ctx context.Context, arg SumModelCallUsageByModelParams) ([]SumModelCallUsageByModelRow, error) {
	rows, err := q.db.Query(ctx, sumModelCallUsageByModel,
		arg.OrgID,
		arg.ProjectID,
		arg.AgentProfileID,
		arg.AgentIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumModelCallUsageByModelRow{}
	for rows.Next() {
		var i SumModelCallUsageByModelRow
		if err := rows.Scan(
			&i.ConfiguredModelID,
			&i.ConfiguredModelName,
			&i.ProviderModelSlug,
			&i.ModelProviderConfigID,
			&i.ModelProviderConfigName,
			&i.ModelCalls,
			&i.ModelCallsWithReportedCost,
			&i.InputTokensTotal,
			&i.UncachedInputTokens,
			&i.CacheReadInputTokens,
			&i.CacheWriteInputTokens,
			&i.OutputTokensTotal,
			&i.ReasoningOutputTokens,
			&i.ProviderReportedCostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
