// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model_provider_configs.sql

package dbsqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const configuredModelHasActiveGrants = `-- name: ConfiguredModelHasActiveGrants :one
SELECT EXISTS (
  SELECT 1
  FROM project_model_grants model_grant
  WHERE model_grant.org_id = $1
    AND model_grant.configured_model_id = $2
) AS has_active_grants
`

type ConfiguredModelHasActiveGrantsParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) ConfiguredModelHasActiveGrants(ctx context.Context, arg ConfiguredModelHasActiveGrantsParams) (bool, error) {
	row := q.db.QueryRow(ctx, configuredModelHasActiveGrants, arg.OrgID, arg.ID)
	var has_active_grants bool
	err := row.Scan(&has_active_grants)
	return has_active_grants, err
}

const deleteConfiguredModel = `-- name: DeleteConfiguredModel :one
UPDATE configured_models
SET deleted_at = statement_timestamp(),
    updated_at = statement_timestamp()
WHERE configured_models.org_id = $1
  AND configured_models.id = $2
  AND configured_models.deleted_at IS NULL
  AND configured_models.management_kind = $3
RETURNING id, org_id, model_provider_config_id, management_kind, name, current_revision_id,
          deleted_at, created_at, updated_at
`

type DeleteConfiguredModelParams struct {
	OrgID          uuid.UUID
	ID             uuid.UUID
	ManagementKind string
}

type DeleteConfiguredModelRow struct {
	ID                    uuid.UUID
	OrgID                 uuid.UUID
	ModelProviderConfigID uuid.UUID
	ManagementKind        string
	Name                  string
	CurrentRevisionID     uuid.UUID
	DeletedAt             *time.Time
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

func (q *Queries) DeleteConfiguredModel(ctx context.Context, arg DeleteConfiguredModelParams) (DeleteConfiguredModelRow, error) {
	row := q.db.QueryRow(ctx, deleteConfiguredModel, arg.OrgID, arg.ID, arg.ManagementKind)
	var i DeleteConfiguredModelRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ModelProviderConfigID,
		&i.ManagementKind,
		&i.Name,
		&i.CurrentRevisionID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteModelProviderConfig = `-- name: DeleteModelProviderConfig :one
UPDATE model_provider_configs
SET deleted_at = statement_timestamp(),
    credential_secret_id = NULL,
    updated_at = statement_timestamp()
WHERE model_provider_configs.org_id = $1
  AND model_provider_configs.id = $2
  AND model_provider_configs.deleted_at IS NULL
  AND model_provider_configs.management_kind = 'tenant'
  AND NOT EXISTS (
    SELECT 1
    FROM configured_models configured_model
    WHERE configured_model.org_id = model_provider_configs.org_id
      AND configured_model.model_provider_config_id = model_provider_configs.id
      AND configured_model.deleted_at IS NULL
  )
RETURNING id, org_id, management_kind, name, api_format, api_variant, base_url, endpoint_path,
          request_timeout_ms, auth_kind, auth_options,
          credential_secret_id, deleted_at, created_at, updated_at, idle_timeout_ms
`

type DeleteModelProviderConfigParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

// Clearing the credential releases the secret for deletion.
func (q *Queries) DeleteModelProviderConfig(ctx context.Context, arg DeleteModelProviderConfigParams) (ModelProviderConfig, error) {
	row := q.db.QueryRow(ctx, deleteModelProviderConfig, arg.OrgID, arg.ID)
	var i ModelProviderConfig
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ManagementKind,
		&i.Name,
		&i.ApiFormat,
		&i.ApiVariant,
		&i.BaseUrl,
		&i.EndpointPath,
		&i.RequestTimeoutMs,
		&i.AuthKind,
		&i.AuthOptions,
		&i.CredentialSecretID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdleTimeoutMs,
	)
	return i, err
}

const deleteProjectModelGrant = `-- name: DeleteProjectModelGrant :one
DELETE FROM project_model_grants
WHERE org_id = $1
  AND project_id = $2
  AND id = $3
RETURNING id, org_id, project_id, configured_model_id,
          context_window_tokens, max_output_tokens, default_max_output_tokens,
          default_cache_retention, supports_tools, supports_reasoning,
          default_reasoning_effort, supported_reasoning_efforts,
          input_modalities, output_modalities,
          created_at, updated_at
`

type DeleteProjectModelGrantParams struct {
	OrgID     uuid.UUID
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) DeleteProjectModelGrant(ctx context.Context, arg DeleteProjectModelGrantParams) (ProjectModelGrant, error) {
	row := q.db.QueryRow(ctx, deleteProjectModelGrant, arg.OrgID, arg.ProjectID, arg.ID)
	var i ProjectModelGrant
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.ConfiguredModelID,
		&i.ContextWindowTokens,
		&i.MaxOutputTokens,
		&i.DefaultMaxOutputTokens,
		&i.DefaultCacheRetention,
		&i.SupportsTools,
		&i.SupportsReasoning,
		&i.DefaultReasoningEffort,
		&i.SupportedReasoningEfforts,
		&i.InputModalities,
		&i.OutputModalities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProjectModelGrantsForConfiguredModel = `-- name: DeleteProjectModelGrantsForConfiguredModel :execrows
DELETE FROM project_model_grants
WHERE org_id = $1
  AND configured_model_id = $2
`

type DeleteProjectModelGrantsForConfiguredModelParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) DeleteProjectModelGrantsForConfiguredModel(ctx context.Context, arg DeleteProjectModelGrantsForConfiguredModelParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectModelGrantsForConfiguredModel, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveProjectModelGrantForConfiguredModel = `-- name: GetActiveProjectModelGrantForConfiguredModel :one
SELECT grant_row.id, grant_row.org_id, grant_row.project_id,
       grant_row.configured_model_id,
       grant_row.context_window_tokens, grant_row.max_output_tokens,
       grant_row.default_max_output_tokens,
       grant_row.default_cache_retention, grant_row.supports_tools,
       grant_row.supports_reasoning, grant_row.default_reasoning_effort,
       grant_row.supported_reasoning_efforts,
       grant_row.input_modalities, grant_row.output_modalities,
       grant_row.created_at, grant_row.updated_at
FROM project_model_grants grant_row
JOIN configured_models configured_model ON configured_model.org_id = grant_row.org_id
  AND configured_model.id = grant_row.configured_model_id
  AND configured_model.deleted_at IS NULL
JOIN model_provider_configs provider_config ON provider_config.org_id = configured_model.org_id
  AND provider_config.id = configured_model.model_provider_config_id
  AND provider_config.deleted_at IS NULL
WHERE grant_row.org_id = $1
  AND grant_row.project_id = $2
  AND grant_row.configured_model_id = $3
`

type GetActiveProjectModelGrantForConfiguredModelParams struct {
	OrgID             uuid.UUID
	ProjectID         uuid.UUID
	ConfiguredModelID uuid.UUID
}

func (q *Queries) GetActiveProjectModelGrantForConfiguredModel(ctx context.Context, arg GetActiveProjectModelGrantForConfiguredModelParams) (ProjectModelGrant, error) {
	row := q.db.QueryRow(ctx, getActiveProjectModelGrantForConfiguredModel, arg.OrgID, arg.ProjectID, arg.ConfiguredModelID)
	var i ProjectModelGrant
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.ConfiguredModelID,
		&i.ContextWindowTokens,
		&i.MaxOutputTokens,
		&i.DefaultMaxOutputTokens,
		&i.DefaultCacheRetention,
		&i.SupportsTools,
		&i.SupportsReasoning,
		&i.DefaultReasoningEffort,
		&i.SupportedReasoningEfforts,
		&i.InputModalities,
		&i.OutputModalities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConfiguredModel = `-- name: GetConfiguredModel :one
SELECT configured_model.id, configured_model.org_id, configured_model.model_provider_config_id,
       configured_model.management_kind, configured_model.name,
       configured_model.current_revision_id, revision.provider_model_slug,
       revision.context_window_tokens, revision.max_output_tokens,
       revision.default_max_output_tokens,
       revision.default_cache_retention, revision.supports_tools, revision.supports_reasoning,
       revision.default_reasoning_effort, revision.supported_reasoning_efforts,
           revision.input_modalities, revision.output_modalities, revision.api_variant_options,
       configured_model.deleted_at, configured_model.created_at, configured_model.updated_at,
       revision.created_at AS revision_created_at
FROM configured_models configured_model
JOIN configured_model_revisions revision ON revision.org_id = configured_model.org_id
  AND revision.configured_model_id = configured_model.id
  AND revision.id = configured_model.current_revision_id
JOIN model_provider_configs provider_config ON provider_config.org_id = configured_model.org_id
  AND provider_config.id = configured_model.model_provider_config_id
  AND provider_config.deleted_at IS NULL
WHERE configured_model.org_id = $1
  AND configured_model.id = $2
  AND configured_model.deleted_at IS NULL
`

type GetConfiguredModelParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

type GetConfiguredModelRow struct {
	ID                        uuid.UUID
	OrgID                     uuid.UUID
	ModelProviderConfigID     uuid.UUID
	ManagementKind            string
	Name                      string
	CurrentRevisionID         uuid.UUID
	ProviderModelSlug         string
	ContextWindowTokens       int32
	MaxOutputTokens           *int32
	DefaultMaxOutputTokens    *int32
	DefaultCacheRetention     *string
	SupportsTools             bool
	SupportsReasoning         bool
	DefaultReasoningEffort    string
	SupportedReasoningEfforts []string
	InputModalities           []string
	OutputModalities          []string
	ApiVariantOptions         json.RawMessage
	DeletedAt                 *time.Time
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	RevisionCreatedAt         time.Time
}

func (q *Queries) GetConfiguredModel(ctx context.Context, arg GetConfiguredModelParams) (GetConfiguredModelRow, error) {
	row := q.db.QueryRow(ctx, getConfiguredModel, arg.OrgID, arg.ID)
	var i GetConfiguredModelRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ModelProviderConfigID,
		&i.ManagementKind,
		&i.Name,
		&i.CurrentRevisionID,
		&i.ProviderModelSlug,
		&i.ContextWindowTokens,
		&i.MaxOutputTokens,
		&i.DefaultMaxOutputTokens,
		&i.DefaultCacheRetention,
		&i.SupportsTools,
		&i.SupportsReasoning,
		&i.DefaultReasoningEffort,
		&i.SupportedReasoningEfforts,
		&i.InputModalities,
		&i.OutputModalities,
		&i.ApiVariantOptions,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevisionCreatedAt,
	)
	return i, err
}

const getConfiguredModelByName = `-- name: GetConfiguredModelByName :one
SELECT configured_model.id, configured_model.org_id, configured_model.model_provider_config_id,
       configured_model.management_kind, configured_model.name,
       configured_model.current_revision_id, revision.provider_model_slug,
       revision.context_window_tokens, revision.max_output_tokens,
       revision.default_max_output_tokens,
       revision.default_cache_retention, revision.supports_tools, revision.supports_reasoning,
       revision.default_reasoning_effort, revision.supported_reasoning_efforts,
           revision.input_modalities, revision.output_modalities, revision.api_variant_options,
       configured_model.deleted_at, configured_model.created_at, configured_model.updated_at,
       revision.created_at AS revision_created_at
FROM configured_models configured_model
JOIN configured_model_revisions revision ON revision.org_id = configured_model.org_id
  AND revision.configured_model_id = configured_model.id
  AND revision.id = configured_model.current_revision_id
JOIN model_provider_configs provider_config ON provider_config.org_id = configured_model.org_id
  AND provider_config.id = configured_model.model_provider_config_id
  AND provider_config.deleted_at IS NULL
WHERE configured_model.org_id = $1
  AND configured_model.model_provider_config_id = $2
  AND configured_model.name = $3
  AND configured_model.deleted_at IS NULL
`

type GetConfiguredModelByNameParams struct {
	OrgID                 uuid.UUID
	ModelProviderConfigID uuid.UUID
	Name                  string
}

type GetConfiguredModelByNameRow struct {
	ID                        uuid.UUID
	OrgID                     uuid.UUID
	ModelProviderConfigID     uuid.UUID
	ManagementKind            string
	Name                      string
	CurrentRevisionID         uuid.UUID
	ProviderModelSlug         string
	ContextWindowTokens       int32
	MaxOutputTokens           *int32
	DefaultMaxOutputTokens    *int32
	DefaultCacheRetention     *string
	SupportsTools             bool
	SupportsReasoning         bool
	DefaultReasoningEffort    string
	SupportedReasoningEfforts []string
	InputModalities           []string
	OutputModalities          []string
	ApiVariantOptions         json.RawMessage
	DeletedAt                 *time.Time
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	RevisionCreatedAt         time.Time
}

func (q *Queries) GetConfiguredModelByName(ctx context.Context, arg GetConfiguredModelByNameParams) (GetConfiguredModelByNameRow, error) {
	row := q.db.QueryRow(ctx, getConfiguredModelByName, arg.OrgID, arg.ModelProviderConfigID, arg.Name)
	var i GetConfiguredModelByNameRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ModelProviderConfigID,
		&i.ManagementKind,
		&i.Name,
		&i.CurrentRevisionID,
		&i.ProviderModelSlug,
		&i.ContextWindowTokens,
		&i.MaxOutputTokens,
		&i.DefaultMaxOutputTokens,
		&i.DefaultCacheRetention,
		&i.SupportsTools,
		&i.SupportsReasoning,
		&i.DefaultReasoningEffort,
		&i.SupportedReasoningEfforts,
		&i.InputModalities,
		&i.OutputModalities,
		&i.ApiVariantOptions,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevisionCreatedAt,
	)
	return i, err
}

const getConfiguredModelDisplay = `-- name: GetConfiguredModelDisplay :one
SELECT configured_model.id, configured_model.org_id, configured_model.model_provider_config_id,
       configured_model.management_kind, configured_model.name,
       configured_model.current_revision_id, revision.provider_model_slug,
       revision.context_window_tokens, revision.max_output_tokens,
       revision.default_max_output_tokens,
       revision.default_cache_retention, revision.supports_tools, revision.supports_reasoning,
       revision.default_reasoning_effort, revision.supported_reasoning_efforts,
           revision.input_modalities, revision.output_modalities, revision.api_variant_options,
       configured_model.deleted_at, configured_model.created_at, configured_model.updated_at,
       revision.created_at AS revision_created_at
FROM configured_models configured_model
JOIN configured_model_revisions revision ON revision.org_id = configured_model.org_id
  AND revision.configured_model_id = configured_model.id
  AND revision.id = configured_model.current_revision_id
JOIN model_provider_configs provider_config ON provider_config.org_id = configured_model.org_id
  AND provider_config.id = configured_model.model_provider_config_id
WHERE configured_model.org_id = $1
  AND configured_model.id = $2
`

type GetConfiguredModelDisplayParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

type GetConfiguredModelDisplayRow struct {
	ID                        uuid.UUID
	OrgID                     uuid.UUID
	ModelProviderConfigID     uuid.UUID
	ManagementKind            string
	Name                      string
	CurrentRevisionID         uuid.UUID
	ProviderModelSlug         string
	ContextWindowTokens       int32
	MaxOutputTokens           *int32
	DefaultMaxOutputTokens    *int32
	DefaultCacheRetention     *string
	SupportsTools             bool
	SupportsReasoning         bool
	DefaultReasoningEffort    string
	SupportedReasoningEfforts []string
	InputModalities           []string
	OutputModalities          []string
	ApiVariantOptions         json.RawMessage
	DeletedAt                 *time.Time
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	RevisionCreatedAt         time.Time
}

func (q *Queries) GetConfiguredModelDisplay(ctx context.Context, arg GetConfiguredModelDisplayParams) (GetConfiguredModelDisplayRow, error) {
	row := q.db.QueryRow(ctx, getConfiguredModelDisplay, arg.OrgID, arg.ID)
	var i GetConfiguredModelDisplayRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ModelProviderConfigID,
		&i.ManagementKind,
		&i.Name,
		&i.CurrentRevisionID,
		&i.ProviderModelSlug,
		&i.ContextWindowTokens,
		&i.MaxOutputTokens,
		&i.DefaultMaxOutputTokens,
		&i.DefaultCacheRetention,
		&i.SupportsTools,
		&i.SupportsReasoning,
		&i.DefaultReasoningEffort,
		&i.SupportedReasoningEfforts,
		&i.InputModalities,
		&i.OutputModalities,
		&i.ApiVariantOptions,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevisionCreatedAt,
	)
	return i, err
}

const getConfiguredModelReferenceState = `-- name: GetConfiguredModelReferenceState :one
SELECT EXISTS (
         SELECT 1
         FROM projects project
         JOIN agents agent ON agent.project_id = project.id
         JOIN agent_configs config ON config.project_id = agent.project_id
           AND config.id = agent.current_config_id
         WHERE project.org_id = $1
           AND agent.state = 'active'
           AND config.configured_model_id = $2
       ) AS used_by_active_agent,
       EXISTS (
         SELECT 1
         FROM projects project
         JOIN agent_profiles profile ON profile.project_id = project.id
         JOIN agent_profile_versions version ON version.project_id = profile.project_id
           AND version.profile_id = profile.id
           AND version.id = profile.current_version_id
           AND version.deleted_at IS NULL
         JOIN agent_configs config ON config.project_id = version.project_id
           AND config.id = version.agent_config_id
         WHERE project.org_id = $1
           AND profile.deleted_at IS NULL
           AND config.configured_model_id = $2
       ) AS used_by_agent_profile
`

type GetConfiguredModelReferenceStateParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

type GetConfiguredModelReferenceStateRow struct {
	UsedByActiveAgent  bool
	UsedByAgentProfile bool
}

func (q *Queries) GetConfiguredModelReferenceState(ctx context.Context, arg GetConfiguredModelReferenceStateParams) (GetConfiguredModelReferenceStateRow, error) {
	row := q.db.QueryRow(ctx, getConfiguredModelReferenceState, arg.OrgID, arg.ID)
	var i GetConfiguredModelReferenceStateRow
	err := row.Scan(&i.UsedByActiveAgent, &i.UsedByAgentProfile)
	return i, err
}

const getConfiguredModelRevisionDisplay = `-- name: GetConfiguredModelRevisionDisplay :one
SELECT revision.id, revision.org_id, revision.configured_model_id,
       revision.model_provider_config_id,
       revision.provider_model_slug, revision.context_window_tokens,
       revision.max_output_tokens, revision.default_max_output_tokens,
       revision.default_cache_retention,
       revision.supports_tools, revision.supports_reasoning,
       revision.default_reasoning_effort,
       revision.supported_reasoning_efforts, revision.input_modalities,
           revision.output_modalities, revision.api_variant_options,
       revision.created_at,
       configured_model.name AS configured_model_name,
       provider_config.name AS provider_config_name,
       provider_config.api_format,
       provider_config.api_variant
FROM configured_model_revisions revision
JOIN configured_models configured_model ON configured_model.org_id = revision.org_id
  AND configured_model.id = revision.configured_model_id
JOIN model_provider_configs provider_config ON provider_config.org_id = revision.org_id
  AND provider_config.id = revision.model_provider_config_id
WHERE revision.org_id = $1
  AND revision.id = $2
`

type GetConfiguredModelRevisionDisplayParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

type GetConfiguredModelRevisionDisplayRow struct {
	ID                        uuid.UUID
	OrgID                     uuid.UUID
	ConfiguredModelID         uuid.UUID
	ModelProviderConfigID     uuid.UUID
	ProviderModelSlug         string
	ContextWindowTokens       int32
	MaxOutputTokens           *int32
	DefaultMaxOutputTokens    *int32
	DefaultCacheRetention     *string
	SupportsTools             bool
	SupportsReasoning         bool
	DefaultReasoningEffort    string
	SupportedReasoningEfforts []string
	InputModalities           []string
	OutputModalities          []string
	ApiVariantOptions         json.RawMessage
	CreatedAt                 time.Time
	ConfiguredModelName       string
	ProviderConfigName        string
	ApiFormat                 string
	ApiVariant                string
}

// @sqlc-vet-disable model-provider-configs-deleted-at configured-models-deleted-at
// Revision display must resolve even when its parents are soft deleted.
func (q *Queries) GetConfiguredModelRevisionDisplay(ctx context.Context, arg GetConfiguredModelRevisionDisplayParams) (GetConfiguredModelRevisionDisplayRow, error) {
	row := q.db.QueryRow(ctx, getConfiguredModelRevisionDisplay, arg.OrgID, arg.ID)
	var i GetConfiguredModelRevisionDisplayRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ConfiguredModelID,
		&i.ModelProviderConfigID,
		&i.ProviderModelSlug,
		&i.ContextWindowTokens,
		&i.MaxOutputTokens,
		&i.DefaultMaxOutputTokens,
		&i.DefaultCacheRetention,
		&i.SupportsTools,
		&i.SupportsReasoning,
		&i.DefaultReasoningEffort,
		&i.SupportedReasoningEfforts,
		&i.InputModalities,
		&i.OutputModalities,
		&i.ApiVariantOptions,
		&i.CreatedAt,
		&i.ConfiguredModelName,
		&i.ProviderConfigName,
		&i.ApiFormat,
		&i.ApiVariant,
	)
	return i, err
}

const getConfiguredModelRevisionForUse = `-- name: GetConfiguredModelRevisionForUse :one
SELECT revision.id, revision.org_id, revision.configured_model_id,
       revision.model_provider_config_id,
       revision.provider_model_slug, revision.context_window_tokens,
       revision.max_output_tokens, revision.default_max_output_tokens,
       revision.default_cache_retention,
       revision.supports_tools, revision.supports_reasoning,
       revision.default_reasoning_effort,
       revision.supported_reasoning_efforts, revision.input_modalities,
           revision.output_modalities, revision.api_variant_options,
       revision.created_at
FROM configured_model_revisions revision
JOIN configured_models configured_model ON configured_model.org_id = revision.org_id
  AND configured_model.id = revision.configured_model_id
  AND configured_model.deleted_at IS NULL
JOIN model_provider_configs provider_config ON provider_config.org_id = revision.org_id
  AND provider_config.id = revision.model_provider_config_id
  AND provider_config.deleted_at IS NULL
WHERE revision.org_id = $1
  AND revision.id = $2
`

type GetConfiguredModelRevisionForUseParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) GetConfiguredModelRevisionForUse(ctx context.Context, arg GetConfiguredModelRevisionForUseParams) (ConfiguredModelRevision, error) {
	row := q.db.QueryRow(ctx, getConfiguredModelRevisionForUse, arg.OrgID, arg.ID)
	var i ConfiguredModelRevision
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ConfiguredModelID,
		&i.ModelProviderConfigID,
		&i.ProviderModelSlug,
		&i.ContextWindowTokens,
		&i.MaxOutputTokens,
		&i.DefaultMaxOutputTokens,
		&i.DefaultCacheRetention,
		&i.SupportsTools,
		&i.SupportsReasoning,
		&i.DefaultReasoningEffort,
		&i.SupportedReasoningEfforts,
		&i.InputModalities,
		&i.OutputModalities,
		&i.ApiVariantOptions,
		&i.CreatedAt,
	)
	return i, err
}

const getModelProviderConfig = `-- name: GetModelProviderConfig :one
SELECT id, org_id, management_kind, name, api_format, api_variant, base_url, endpoint_path,
       request_timeout_ms, auth_kind, auth_options,
       credential_secret_id, deleted_at,
       created_at, updated_at, idle_timeout_ms
FROM model_provider_configs
WHERE org_id = $1
  AND id = $2
  AND deleted_at IS NULL
`

type GetModelProviderConfigParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) GetModelProviderConfig(ctx context.Context, arg GetModelProviderConfigParams) (ModelProviderConfig, error) {
	row := q.db.QueryRow(ctx, getModelProviderConfig, arg.OrgID, arg.ID)
	var i ModelProviderConfig
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ManagementKind,
		&i.Name,
		&i.ApiFormat,
		&i.ApiVariant,
		&i.BaseUrl,
		&i.EndpointPath,
		&i.RequestTimeoutMs,
		&i.AuthKind,
		&i.AuthOptions,
		&i.CredentialSecretID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdleTimeoutMs,
	)
	return i, err
}

const getModelProviderConfigByName = `-- name: GetModelProviderConfigByName :one
SELECT id, org_id, management_kind, name, api_format, api_variant, base_url, endpoint_path,
       request_timeout_ms, auth_kind, auth_options,
       credential_secret_id, deleted_at,
       created_at, updated_at, idle_timeout_ms
FROM model_provider_configs
WHERE org_id = $1
  AND name = $2
  AND deleted_at IS NULL
`

type GetModelProviderConfigByNameParams struct {
	OrgID uuid.UUID
	Name  string
}

func (q *Queries) GetModelProviderConfigByName(ctx context.Context, arg GetModelProviderConfigByNameParams) (ModelProviderConfig, error) {
	row := q.db.QueryRow(ctx, getModelProviderConfigByName, arg.OrgID, arg.Name)
	var i ModelProviderConfig
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ManagementKind,
		&i.Name,
		&i.ApiFormat,
		&i.ApiVariant,
		&i.BaseUrl,
		&i.EndpointPath,
		&i.RequestTimeoutMs,
		&i.AuthKind,
		&i.AuthOptions,
		&i.CredentialSecretID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdleTimeoutMs,
	)
	return i, err
}

const getProjectModelGrant = `-- name: GetProjectModelGrant :one
SELECT id, org_id, project_id, configured_model_id,
       context_window_tokens, max_output_tokens, default_max_output_tokens,
       default_cache_retention, supports_tools, supports_reasoning,
       default_reasoning_effort, supported_reasoning_efforts,
       input_modalities, output_modalities,
       created_at, updated_at
FROM project_model_grants
WHERE org_id = $1
  AND project_id = $2
  AND id = $3
`

type GetProjectModelGrantParams struct {
	OrgID     uuid.UUID
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetProjectModelGrant(ctx context.Context, arg GetProjectModelGrantParams) (ProjectModelGrant, error) {
	row := q.db.QueryRow(ctx, getProjectModelGrant, arg.OrgID, arg.ProjectID, arg.ID)
	var i ProjectModelGrant
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.ConfiguredModelID,
		&i.ContextWindowTokens,
		&i.MaxOutputTokens,
		&i.DefaultMaxOutputTokens,
		&i.DefaultCacheRetention,
		&i.SupportsTools,
		&i.SupportsReasoning,
		&i.DefaultReasoningEffort,
		&i.SupportedReasoningEfforts,
		&i.InputModalities,
		&i.OutputModalities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertConfiguredModel = `-- name: InsertConfiguredModel :one
WITH ids AS (
  SELECT uuidv7() AS configured_model_id, uuidv7() AS revision_id
),
parent_config AS (
  SELECT config.org_id, config.id
  FROM model_provider_configs config
  WHERE config.org_id = $1
    AND config.id = $2
    AND config.deleted_at IS NULL
),
configured_model AS (
  INSERT INTO configured_models(
    id, org_id, model_provider_config_id, management_kind, name, current_revision_id,
    created_at, updated_at
  )
  SELECT ids.configured_model_id, config.org_id, config.id,
         $3::text, $4,
         ids.revision_id, statement_timestamp(), statement_timestamp()
  FROM ids
  JOIN parent_config config ON true
  RETURNING id, org_id, model_provider_config_id, management_kind, name, current_revision_id,
            deleted_at, created_at, updated_at
),
revision AS (
  INSERT INTO configured_model_revisions(
    id, org_id, configured_model_id, model_provider_config_id, provider_model_slug,
    context_window_tokens, max_output_tokens, default_max_output_tokens,
        default_cache_retention, supports_tools, supports_reasoning, default_reasoning_effort,
        supported_reasoning_efforts, input_modalities, output_modalities,
        api_variant_options, created_at
  )
  SELECT configured_model.current_revision_id, configured_model.org_id, configured_model.id,
         configured_model.model_provider_config_id, $5,
         $6, $7,
         $8,
         $9, $10::bool,
         $11::bool, $12::text,
             $13::text[],
             $14::text[], $15::text[],
             $16, statement_timestamp()
  FROM configured_model
  RETURNING id, org_id, configured_model_id, model_provider_config_id,
            provider_model_slug, context_window_tokens, max_output_tokens,
            default_max_output_tokens,
                default_cache_retention, supports_tools, supports_reasoning,
                default_reasoning_effort, supported_reasoning_efforts,
                input_modalities, output_modalities, api_variant_options, created_at
)
SELECT configured_model.id, configured_model.org_id, configured_model.model_provider_config_id,
       configured_model.management_kind, configured_model.name,
       configured_model.current_revision_id, revision.provider_model_slug,
       revision.context_window_tokens, revision.max_output_tokens,
       revision.default_max_output_tokens,
       revision.default_cache_retention, revision.supports_tools, revision.supports_reasoning,
       revision.default_reasoning_effort, revision.supported_reasoning_efforts,
           revision.input_modalities, revision.output_modalities, revision.api_variant_options,
       configured_model.deleted_at, configured_model.created_at, configured_model.updated_at,
       revision.created_at AS revision_created_at
FROM configured_model
JOIN revision ON revision.configured_model_id = configured_model.id
`

type InsertConfiguredModelParams struct {
	OrgID                     uuid.UUID
	ModelProviderConfigID     uuid.UUID
	ManagementKind            string
	Name                      string
	ProviderModelSlug         string
	ContextWindowTokens       int32
	MaxOutputTokens           *int32
	DefaultMaxOutputTokens    *int32
	DefaultCacheRetention     *string
	SupportsTools             bool
	SupportsReasoning         bool
	DefaultReasoningEffort    string
	SupportedReasoningEfforts []string
	InputModalities           []string
	OutputModalities          []string
	ApiVariantOptions         json.RawMessage
}

type InsertConfiguredModelRow struct {
	ID                        uuid.UUID
	OrgID                     uuid.UUID
	ModelProviderConfigID     uuid.UUID
	ManagementKind            string
	Name                      string
	CurrentRevisionID         uuid.UUID
	ProviderModelSlug         string
	ContextWindowTokens       int32
	MaxOutputTokens           *int32
	DefaultMaxOutputTokens    *int32
	DefaultCacheRetention     *string
	SupportsTools             bool
	SupportsReasoning         bool
	DefaultReasoningEffort    string
	SupportedReasoningEfforts []string
	InputModalities           []string
	OutputModalities          []string
	ApiVariantOptions         json.RawMessage
	DeletedAt                 *time.Time
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	RevisionCreatedAt         time.Time
}

func (q *Queries) InsertConfiguredModel(ctx context.Context, arg InsertConfiguredModelParams) (InsertConfiguredModelRow, error) {
	row := q.db.QueryRow(ctx, insertConfiguredModel,
		arg.OrgID,
		arg.ModelProviderConfigID,
		arg.ManagementKind,
		arg.Name,
		arg.ProviderModelSlug,
		arg.ContextWindowTokens,
		arg.MaxOutputTokens,
		arg.DefaultMaxOutputTokens,
		arg.DefaultCacheRetention,
		arg.SupportsTools,
		arg.SupportsReasoning,
		arg.DefaultReasoningEffort,
		arg.SupportedReasoningEfforts,
		arg.InputModalities,
		arg.OutputModalities,
		arg.ApiVariantOptions,
	)
	var i InsertConfiguredModelRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ModelProviderConfigID,
		&i.ManagementKind,
		&i.Name,
		&i.CurrentRevisionID,
		&i.ProviderModelSlug,
		&i.ContextWindowTokens,
		&i.MaxOutputTokens,
		&i.DefaultMaxOutputTokens,
		&i.DefaultCacheRetention,
		&i.SupportsTools,
		&i.SupportsReasoning,
		&i.DefaultReasoningEffort,
		&i.SupportedReasoningEfforts,
		&i.InputModalities,
		&i.OutputModalities,
		&i.ApiVariantOptions,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevisionCreatedAt,
	)
	return i, err
}

const insertModelProviderConfig = `-- name: InsertModelProviderConfig :one
INSERT INTO model_provider_configs(
  org_id, management_kind, name, api_format, api_variant, base_url, endpoint_path,
  request_timeout_ms, idle_timeout_ms, auth_kind, auth_options, credential_secret_id,
  created_at, updated_at
)
SELECT org.id, $1, $2, $3, $4,
       $5, $6,
       $7, $8, $9, $10,
       $11,
       transaction_timestamp(), transaction_timestamp()
FROM orgs org
JOIN secrets credential ON credential.org_id = org.id
  AND credential.id = $11
  AND credential.deleted_at IS NULL
  AND credential.management_kind = $1
  AND credential.owner_kind = 'org'
WHERE org.id = $12
RETURNING id, org_id, management_kind, name, api_format, api_variant, base_url, endpoint_path,
          request_timeout_ms, auth_kind, auth_options,
          credential_secret_id, deleted_at, created_at, updated_at, idle_timeout_ms
`

type InsertModelProviderConfigParams struct {
	ManagementKind     string
	Name               string
	ApiFormat          string
	ApiVariant         string
	BaseUrl            string
	EndpointPath       string
	RequestTimeoutMs   int32
	IdleTimeoutMs      int32
	AuthKind           string
	AuthOptions        json.RawMessage
	CredentialSecretID *uuid.UUID
	OrgID              uuid.UUID
}

func (q *Queries) InsertModelProviderConfig(ctx context.Context, arg InsertModelProviderConfigParams) (ModelProviderConfig, error) {
	row := q.db.QueryRow(ctx, insertModelProviderConfig,
		arg.ManagementKind,
		arg.Name,
		arg.ApiFormat,
		arg.ApiVariant,
		arg.BaseUrl,
		arg.EndpointPath,
		arg.RequestTimeoutMs,
		arg.IdleTimeoutMs,
		arg.AuthKind,
		arg.AuthOptions,
		arg.CredentialSecretID,
		arg.OrgID,
	)
	var i ModelProviderConfig
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ManagementKind,
		&i.Name,
		&i.ApiFormat,
		&i.ApiVariant,
		&i.BaseUrl,
		&i.EndpointPath,
		&i.RequestTimeoutMs,
		&i.AuthKind,
		&i.AuthOptions,
		&i.CredentialSecretID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdleTimeoutMs,
	)
	return i, err
}

const insertProjectModelGrant = `-- name: InsertProjectModelGrant :one
INSERT INTO project_model_grants(
  org_id, project_id, configured_model_id,
  context_window_tokens, max_output_tokens, default_max_output_tokens,
  default_cache_retention, supports_tools, supports_reasoning,
  default_reasoning_effort, supported_reasoning_efforts,
  input_modalities, output_modalities,
  created_at, updated_at
)
SELECT project.org_id, project.id, configured_model.id,
       $1, $2,
       $3,
       $4, $5,
       $6, $7::text,
       $8::text[],
       $9::text[], $10::text[],
       statement_timestamp(), statement_timestamp()
FROM projects project
JOIN configured_models configured_model ON configured_model.org_id = project.org_id
  AND configured_model.id = $11
  AND configured_model.deleted_at IS NULL
JOIN model_provider_configs provider_config ON provider_config.org_id = configured_model.org_id
  AND provider_config.id = configured_model.model_provider_config_id
  AND provider_config.deleted_at IS NULL
WHERE project.org_id = $12
  AND project.id = $13
RETURNING id, org_id, project_id, configured_model_id,
          context_window_tokens, max_output_tokens, default_max_output_tokens,
          default_cache_retention, supports_tools, supports_reasoning,
          default_reasoning_effort, supported_reasoning_efforts,
          input_modalities, output_modalities,
          created_at, updated_at
`

type InsertProjectModelGrantParams struct {
	ContextWindowTokens       *int32
	MaxOutputTokens           *int32
	DefaultMaxOutputTokens    *int32
	DefaultCacheRetention     *string
	SupportsTools             *bool
	SupportsReasoning         *bool
	DefaultReasoningEffort    string
	SupportedReasoningEfforts []string
	InputModalities           []string
	OutputModalities          []string
	ConfiguredModelID         uuid.UUID
	OrgID                     uuid.UUID
	ProjectID                 uuid.UUID
}

func (q *Queries) InsertProjectModelGrant(ctx context.Context, arg InsertProjectModelGrantParams) (ProjectModelGrant, error) {
	row := q.db.QueryRow(ctx, insertProjectModelGrant,
		arg.ContextWindowTokens,
		arg.MaxOutputTokens,
		arg.DefaultMaxOutputTokens,
		arg.DefaultCacheRetention,
		arg.SupportsTools,
		arg.SupportsReasoning,
		arg.DefaultReasoningEffort,
		arg.SupportedReasoningEfforts,
		arg.InputModalities,
		arg.OutputModalities,
		arg.ConfiguredModelID,
		arg.OrgID,
		arg.ProjectID,
	)
	var i ProjectModelGrant
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.ConfiguredModelID,
		&i.ContextWindowTokens,
		&i.MaxOutputTokens,
		&i.DefaultMaxOutputTokens,
		&i.DefaultCacheRetention,
		&i.SupportsTools,
		&i.SupportsReasoning,
		&i.DefaultReasoningEffort,
		&i.SupportedReasoningEfforts,
		&i.InputModalities,
		&i.OutputModalities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClusterManagedModelProviderConfigsByName = `-- name: ListClusterManagedModelProviderConfigsByName :many
SELECT id, org_id, management_kind, name, api_format, api_variant, base_url, endpoint_path,
       request_timeout_ms, auth_kind, auth_options,
       credential_secret_id, deleted_at, created_at, updated_at, idle_timeout_ms
FROM model_provider_configs
WHERE name = $1
  AND management_kind = 'cluster'
  AND deleted_at IS NULL
ORDER BY org_id, id
`

type ListClusterManagedModelProviderConfigsByNameParams struct {
	Name string
}

func (q *Queries) ListClusterManagedModelProviderConfigsByName(ctx context.Context, arg ListClusterManagedModelProviderConfigsByNameParams) ([]ModelProviderConfig, error) {
	rows, err := q.db.Query(ctx, listClusterManagedModelProviderConfigsByName, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelProviderConfig{}
	for rows.Next() {
		var i ModelProviderConfig
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ManagementKind,
			&i.Name,
			&i.ApiFormat,
			&i.ApiVariant,
			&i.BaseUrl,
			&i.EndpointPath,
			&i.RequestTimeoutMs,
			&i.AuthKind,
			&i.AuthOptions,
			&i.CredentialSecretID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IdleTimeoutMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfiguredModels = `-- name: ListConfiguredModels :many
SELECT configured_model.id, configured_model.org_id, configured_model.model_provider_config_id,
       configured_model.management_kind, configured_model.name,
       configured_model.current_revision_id, revision.provider_model_slug,
       revision.context_window_tokens, revision.max_output_tokens,
       revision.default_max_output_tokens,
       revision.default_cache_retention, revision.supports_tools, revision.supports_reasoning,
       revision.default_reasoning_effort, revision.supported_reasoning_efforts,
           revision.input_modalities, revision.output_modalities, revision.api_variant_options,
       configured_model.deleted_at, configured_model.created_at, configured_model.updated_at,
       revision.created_at AS revision_created_at
FROM configured_models configured_model
JOIN configured_model_revisions revision ON revision.org_id = configured_model.org_id
  AND revision.configured_model_id = configured_model.id
  AND revision.id = configured_model.current_revision_id
JOIN model_provider_configs provider_config ON provider_config.org_id = configured_model.org_id
  AND provider_config.id = configured_model.model_provider_config_id
  AND provider_config.deleted_at IS NULL
WHERE configured_model.org_id = $1
  AND configured_model.model_provider_config_id = $2
  AND configured_model.deleted_at IS NULL
  AND (
    $3::timestamptz IS NULL
    OR (configured_model.created_at, configured_model.id) < ($3::timestamptz, $4::uuid)
  )
ORDER BY configured_model.created_at DESC, configured_model.id DESC
LIMIT $5::bigint
`

type ListConfiguredModelsParams struct {
	OrgID                 uuid.UUID
	ModelProviderConfigID uuid.UUID
	CursorCreatedAt       *time.Time
	CursorID              *uuid.UUID
	RowLimit              int64
}

type ListConfiguredModelsRow struct {
	ID                        uuid.UUID
	OrgID                     uuid.UUID
	ModelProviderConfigID     uuid.UUID
	ManagementKind            string
	Name                      string
	CurrentRevisionID         uuid.UUID
	ProviderModelSlug         string
	ContextWindowTokens       int32
	MaxOutputTokens           *int32
	DefaultMaxOutputTokens    *int32
	DefaultCacheRetention     *string
	SupportsTools             bool
	SupportsReasoning         bool
	DefaultReasoningEffort    string
	SupportedReasoningEfforts []string
	InputModalities           []string
	OutputModalities          []string
	ApiVariantOptions         json.RawMessage
	DeletedAt                 *time.Time
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	RevisionCreatedAt         time.Time
}

func (q *Queries) ListConfiguredModels(ctx context.Context, arg ListConfiguredModelsParams) ([]ListConfiguredModelsRow, error) {
	rows, err := q.db.Query(ctx, listConfiguredModels,
		arg.OrgID,
		arg.ModelProviderConfigID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConfiguredModelsRow{}
	for rows.Next() {
		var i ListConfiguredModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ModelProviderConfigID,
			&i.ManagementKind,
			&i.Name,
			&i.CurrentRevisionID,
			&i.ProviderModelSlug,
			&i.ContextWindowTokens,
			&i.MaxOutputTokens,
			&i.DefaultMaxOutputTokens,
			&i.DefaultCacheRetention,
			&i.SupportsTools,
			&i.SupportsReasoning,
			&i.DefaultReasoningEffort,
			&i.SupportedReasoningEfforts,
			&i.InputModalities,
			&i.OutputModalities,
			&i.ApiVariantOptions,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RevisionCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelProviderConfigs = `-- name: ListModelProviderConfigs :many
WITH listed AS (
 SELECT id, org_id, management_kind, name, api_format, api_variant, base_url, endpoint_path,
        request_timeout_ms, auth_kind, auth_options,
        credential_secret_id, deleted_at, created_at, updated_at, idle_timeout_ms,
        CASE $6::text
          WHEN 'name' THEN lower(name)
          WHEN 'created_at' THEN to_char(created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US')
          WHEN 'updated_at' THEN to_char(updated_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US')
        END::text AS sort_key,
        false AS sort_is_null
 FROM model_provider_configs
 WHERE org_id = $7
   AND deleted_at IS NULL
   AND ($8::text = '' OR name ILIKE $8::text ESCAPE '\')
)
SELECT id, org_id, management_kind, name, api_format, api_variant, base_url, endpoint_path,
       request_timeout_ms, auth_kind, auth_options,
       credential_secret_id, deleted_at, created_at, updated_at, idle_timeout_ms,
       sort_key, sort_is_null
FROM listed
WHERE $1::boolean = false
   OR ($2::boolean = false AND (sort_key, id) > ($3::text, $4::uuid))
   OR ($2::boolean = true AND (sort_key, id) < ($3::text, $4::uuid))
ORDER BY CASE WHEN NOT $2::boolean THEN sort_key END ASC,
         CASE WHEN $2::boolean THEN sort_key END DESC,
         CASE WHEN NOT $2::boolean THEN id END ASC,
         CASE WHEN $2::boolean THEN id END DESC
LIMIT $5::bigint
`

type ListModelProviderConfigsParams struct {
	CursorSet   bool
	SortDesc    bool
	CursorKey   string
	CursorID    uuid.UUID
	RowLimit    int64
	SortField   string
	OrgID       uuid.UUID
	NamePattern string
}

type ListModelProviderConfigsRow struct {
	ID                 uuid.UUID
	OrgID              uuid.UUID
	ManagementKind     string
	Name               string
	ApiFormat          string
	ApiVariant         string
	BaseUrl            string
	EndpointPath       string
	RequestTimeoutMs   int32
	AuthKind           string
	AuthOptions        json.RawMessage
	CredentialSecretID *uuid.UUID
	DeletedAt          *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	IdleTimeoutMs      int32
	SortKey            string
	SortIsNull         bool
}

func (q *Queries) ListModelProviderConfigs(ctx context.Context, arg ListModelProviderConfigsParams) ([]ListModelProviderConfigsRow, error) {
	rows, err := q.db.Query(ctx, listModelProviderConfigs,
		arg.CursorSet,
		arg.SortDesc,
		arg.CursorKey,
		arg.CursorID,
		arg.RowLimit,
		arg.SortField,
		arg.OrgID,
		arg.NamePattern,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModelProviderConfigsRow{}
	for rows.Next() {
		var i ListModelProviderConfigsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ManagementKind,
			&i.Name,
			&i.ApiFormat,
			&i.ApiVariant,
			&i.BaseUrl,
			&i.EndpointPath,
			&i.RequestTimeoutMs,
			&i.AuthKind,
			&i.AuthOptions,
			&i.CredentialSecretID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IdleTimeoutMs,
			&i.SortKey,
			&i.SortIsNull,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectModelGrants = `-- name: ListProjectModelGrants :many
WITH listed AS (
 SELECT g.id, g.org_id, g.project_id, g.configured_model_id,
       g.context_window_tokens, g.max_output_tokens, g.default_max_output_tokens,
       g.default_cache_retention, g.supports_tools, g.supports_reasoning,
       g.default_reasoning_effort, g.supported_reasoning_efforts,
       g.input_modalities, g.output_modalities,
       g.created_at, g.updated_at,
       configured_model.name AS model_name, configured_model.model_provider_config_id,
       provider_config.name AS provider_config_name,
       revision.provider_model_slug,
       configured_model.created_at AS model_created_at, configured_model.updated_at AS model_updated_at,
       CASE $6::text WHEN 'name' THEN lower(configured_model.name) WHEN 'created_at' THEN to_char(g.created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US') WHEN 'updated_at' THEN to_char(g.updated_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US') END::text AS sort_key, false AS sort_is_null
 FROM project_model_grants g
 JOIN configured_models configured_model ON configured_model.org_id = g.org_id
  AND configured_model.id = g.configured_model_id
  AND configured_model.deleted_at IS NULL
 JOIN model_provider_configs provider_config ON provider_config.org_id = configured_model.org_id
  AND provider_config.id = configured_model.model_provider_config_id
  AND provider_config.deleted_at IS NULL
 JOIN configured_model_revisions revision ON revision.org_id = configured_model.org_id
  AND revision.id = configured_model.current_revision_id
 WHERE g.org_id = $7
  AND g.project_id = $8
  AND ($9::text = '' OR configured_model.name ILIKE $9::text ESCAPE '\')
)
SELECT id, org_id, project_id, configured_model_id,
 context_window_tokens, max_output_tokens, default_max_output_tokens,
 default_cache_retention, supports_tools, supports_reasoning,
 default_reasoning_effort, supported_reasoning_efforts,
 input_modalities, output_modalities,
 created_at, updated_at,
 model_name, model_provider_config_id, provider_config_name, provider_model_slug,
 model_created_at, model_updated_at,
 sort_key, sort_is_null
FROM listed WHERE $1::boolean = false
 OR ($2::boolean = false AND (sort_key, id) > ($3::text, $4::uuid))
 OR ($2::boolean = true AND (sort_key, id) < ($3::text, $4::uuid))
ORDER BY CASE WHEN NOT $2::boolean THEN sort_key END ASC, CASE WHEN $2::boolean THEN sort_key END DESC,
 CASE WHEN NOT $2::boolean THEN id END ASC, CASE WHEN $2::boolean THEN id END DESC
LIMIT $5::bigint
`

type ListProjectModelGrantsParams struct {
	CursorSet   bool
	SortDesc    bool
	CursorKey   string
	CursorID    uuid.UUID
	RowLimit    int64
	SortField   string
	OrgID       uuid.UUID
	ProjectID   uuid.UUID
	NamePattern string
}

type ListProjectModelGrantsRow struct {
	ID                        uuid.UUID
	OrgID                     uuid.UUID
	ProjectID                 uuid.UUID
	ConfiguredModelID         uuid.UUID
	ContextWindowTokens       *int32
	MaxOutputTokens           *int32
	DefaultMaxOutputTokens    *int32
	DefaultCacheRetention     *string
	SupportsTools             *bool
	SupportsReasoning         *bool
	DefaultReasoningEffort    string
	SupportedReasoningEfforts []string
	InputModalities           []string
	OutputModalities          []string
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	ModelName                 string
	ModelProviderConfigID     uuid.UUID
	ProviderConfigName        string
	ProviderModelSlug         string
	ModelCreatedAt            time.Time
	ModelUpdatedAt            time.Time
	SortKey                   string
	SortIsNull                bool
}

func (q *Queries) ListProjectModelGrants(ctx context.Context, arg ListProjectModelGrantsParams) ([]ListProjectModelGrantsRow, error) {
	rows, err := q.db.Query(ctx, listProjectModelGrants,
		arg.CursorSet,
		arg.SortDesc,
		arg.CursorKey,
		arg.CursorID,
		arg.RowLimit,
		arg.SortField,
		arg.OrgID,
		arg.ProjectID,
		arg.NamePattern,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectModelGrantsRow{}
	for rows.Next() {
		var i ListProjectModelGrantsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.ConfiguredModelID,
			&i.ContextWindowTokens,
			&i.MaxOutputTokens,
			&i.DefaultMaxOutputTokens,
			&i.DefaultCacheRetention,
			&i.SupportsTools,
			&i.SupportsReasoning,
			&i.DefaultReasoningEffort,
			&i.SupportedReasoningEfforts,
			&i.InputModalities,
			&i.OutputModalities,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModelName,
			&i.ModelProviderConfigID,
			&i.ProviderConfigName,
			&i.ProviderModelSlug,
			&i.ModelCreatedAt,
			&i.ModelUpdatedAt,
			&i.SortKey,
			&i.SortIsNull,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockConfiguredModelForDelete = `-- name: LockConfiguredModelForDelete :one
SELECT configured_model.id, configured_model.org_id, configured_model.model_provider_config_id,
       configured_model.name, configured_model.current_revision_id, configured_model.deleted_at,
       configured_model.created_at, configured_model.updated_at, configured_model.management_kind
FROM configured_models configured_model
WHERE configured_model.org_id = $1
  AND configured_model.id = $2
  AND configured_model.deleted_at IS NULL
FOR UPDATE OF configured_model
`

type LockConfiguredModelForDeleteParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) LockConfiguredModelForDelete(ctx context.Context, arg LockConfiguredModelForDeleteParams) (ConfiguredModel, error) {
	row := q.db.QueryRow(ctx, lockConfiguredModelForDelete, arg.OrgID, arg.ID)
	var i ConfiguredModel
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ModelProviderConfigID,
		&i.Name,
		&i.CurrentRevisionID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ManagementKind,
	)
	return i, err
}

const lockConfiguredModelForMutation = `-- name: LockConfiguredModelForMutation :one
SELECT configured_model.id, configured_model.org_id, configured_model.model_provider_config_id,
       configured_model.name, configured_model.current_revision_id, configured_model.deleted_at,
       configured_model.created_at, configured_model.updated_at, configured_model.management_kind
FROM configured_models configured_model
JOIN model_provider_configs provider_config ON provider_config.org_id = configured_model.org_id
  AND provider_config.id = configured_model.model_provider_config_id
  AND provider_config.deleted_at IS NULL
WHERE configured_model.org_id = $1
  AND configured_model.id = $2
  AND configured_model.deleted_at IS NULL
FOR UPDATE OF configured_model
`

type LockConfiguredModelForMutationParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) LockConfiguredModelForMutation(ctx context.Context, arg LockConfiguredModelForMutationParams) (ConfiguredModel, error) {
	row := q.db.QueryRow(ctx, lockConfiguredModelForMutation, arg.OrgID, arg.ID)
	var i ConfiguredModel
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ModelProviderConfigID,
		&i.Name,
		&i.CurrentRevisionID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ManagementKind,
	)
	return i, err
}

const lockConfiguredModelForUse = `-- name: LockConfiguredModelForUse :one
SELECT configured_model.id, configured_model.org_id, configured_model.model_provider_config_id,
       configured_model.management_kind, configured_model.name,
       configured_model.current_revision_id, revision.provider_model_slug,
       revision.context_window_tokens, revision.max_output_tokens,
       revision.default_max_output_tokens,
       revision.default_cache_retention, revision.supports_tools, revision.supports_reasoning,
       revision.default_reasoning_effort, revision.supported_reasoning_efforts,
           revision.input_modalities, revision.output_modalities, revision.api_variant_options,
       configured_model.deleted_at, configured_model.created_at, configured_model.updated_at,
       revision.created_at AS revision_created_at
FROM configured_models configured_model
JOIN configured_model_revisions revision ON revision.org_id = configured_model.org_id
  AND revision.configured_model_id = configured_model.id
  AND revision.id = configured_model.current_revision_id
JOIN model_provider_configs provider_config ON provider_config.org_id = configured_model.org_id
  AND provider_config.id = configured_model.model_provider_config_id
  AND provider_config.deleted_at IS NULL
WHERE configured_model.org_id = $1
  AND configured_model.id = $2
  AND configured_model.deleted_at IS NULL
FOR SHARE OF configured_model
`

type LockConfiguredModelForUseParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

type LockConfiguredModelForUseRow struct {
	ID                        uuid.UUID
	OrgID                     uuid.UUID
	ModelProviderConfigID     uuid.UUID
	ManagementKind            string
	Name                      string
	CurrentRevisionID         uuid.UUID
	ProviderModelSlug         string
	ContextWindowTokens       int32
	MaxOutputTokens           *int32
	DefaultMaxOutputTokens    *int32
	DefaultCacheRetention     *string
	SupportsTools             bool
	SupportsReasoning         bool
	DefaultReasoningEffort    string
	SupportedReasoningEfforts []string
	InputModalities           []string
	OutputModalities          []string
	ApiVariantOptions         json.RawMessage
	DeletedAt                 *time.Time
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	RevisionCreatedAt         time.Time
}

func (q *Queries) LockConfiguredModelForUse(ctx context.Context, arg LockConfiguredModelForUseParams) (LockConfiguredModelForUseRow, error) {
	row := q.db.QueryRow(ctx, lockConfiguredModelForUse, arg.OrgID, arg.ID)
	var i LockConfiguredModelForUseRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ModelProviderConfigID,
		&i.ManagementKind,
		&i.Name,
		&i.CurrentRevisionID,
		&i.ProviderModelSlug,
		&i.ContextWindowTokens,
		&i.MaxOutputTokens,
		&i.DefaultMaxOutputTokens,
		&i.DefaultCacheRetention,
		&i.SupportsTools,
		&i.SupportsReasoning,
		&i.DefaultReasoningEffort,
		&i.SupportedReasoningEfforts,
		&i.InputModalities,
		&i.OutputModalities,
		&i.ApiVariantOptions,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevisionCreatedAt,
	)
	return i, err
}

const lockModelProviderConfigForConfiguredModelCreate = `-- name: LockModelProviderConfigForConfiguredModelCreate :one
SELECT id, management_kind, api_format, api_variant
FROM model_provider_configs
WHERE org_id = $1
  AND id = $2
  AND deleted_at IS NULL
FOR SHARE
`

type LockModelProviderConfigForConfiguredModelCreateParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

type LockModelProviderConfigForConfiguredModelCreateRow struct {
	ID             uuid.UUID
	ManagementKind string
	ApiFormat      string
	ApiVariant     string
}

func (q *Queries) LockModelProviderConfigForConfiguredModelCreate(ctx context.Context, arg LockModelProviderConfigForConfiguredModelCreateParams) (LockModelProviderConfigForConfiguredModelCreateRow, error) {
	row := q.db.QueryRow(ctx, lockModelProviderConfigForConfiguredModelCreate, arg.OrgID, arg.ID)
	var i LockModelProviderConfigForConfiguredModelCreateRow
	err := row.Scan(
		&i.ID,
		&i.ManagementKind,
		&i.ApiFormat,
		&i.ApiVariant,
	)
	return i, err
}

const lockModelProviderConfigForMutation = `-- name: LockModelProviderConfigForMutation :one
SELECT id, org_id, management_kind, name, api_format, api_variant, base_url, endpoint_path,
       request_timeout_ms, auth_kind, auth_options,
       credential_secret_id, deleted_at,
       created_at, updated_at, idle_timeout_ms
FROM model_provider_configs
WHERE org_id = $1
  AND id = $2
  AND deleted_at IS NULL
FOR UPDATE
`

type LockModelProviderConfigForMutationParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) LockModelProviderConfigForMutation(ctx context.Context, arg LockModelProviderConfigForMutationParams) (ModelProviderConfig, error) {
	row := q.db.QueryRow(ctx, lockModelProviderConfigForMutation, arg.OrgID, arg.ID)
	var i ModelProviderConfig
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ManagementKind,
		&i.Name,
		&i.ApiFormat,
		&i.ApiVariant,
		&i.BaseUrl,
		&i.EndpointPath,
		&i.RequestTimeoutMs,
		&i.AuthKind,
		&i.AuthOptions,
		&i.CredentialSecretID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdleTimeoutMs,
	)
	return i, err
}

const modelProviderConfigHasActiveModels = `-- name: ModelProviderConfigHasActiveModels :one
SELECT EXISTS (
  SELECT 1
  FROM configured_models configured_model
  WHERE configured_model.org_id = $1
    AND configured_model.model_provider_config_id = $2
    AND configured_model.deleted_at IS NULL
) AS has_active_models
`

type ModelProviderConfigHasActiveModelsParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) ModelProviderConfigHasActiveModels(ctx context.Context, arg ModelProviderConfigHasActiveModelsParams) (bool, error) {
	row := q.db.QueryRow(ctx, modelProviderConfigHasActiveModels, arg.OrgID, arg.ID)
	var has_active_models bool
	err := row.Scan(&has_active_models)
	return has_active_models, err
}

const renameConfiguredModel = `-- name: RenameConfiguredModel :one
WITH configured_model AS (
  UPDATE configured_models configured_model
  SET name = $1,
      updated_at = statement_timestamp()
  FROM model_provider_configs provider_config
  WHERE configured_model.org_id = $2
    AND configured_model.model_provider_config_id = $3
    AND configured_model.id = $4
    AND configured_model.deleted_at IS NULL
    AND provider_config.org_id = configured_model.org_id
    AND provider_config.id = configured_model.model_provider_config_id
    AND provider_config.deleted_at IS NULL
    AND configured_model.management_kind = 'tenant'
  RETURNING configured_model.id, configured_model.org_id, configured_model.model_provider_config_id,
            configured_model.management_kind, configured_model.name,
            configured_model.current_revision_id, configured_model.deleted_at,
            configured_model.created_at, configured_model.updated_at
)
SELECT configured_model.id, configured_model.org_id, configured_model.model_provider_config_id,
       configured_model.management_kind, configured_model.name,
       configured_model.current_revision_id, revision.provider_model_slug,
       revision.context_window_tokens, revision.max_output_tokens,
       revision.default_max_output_tokens,
       revision.default_cache_retention, revision.supports_tools, revision.supports_reasoning,
       revision.default_reasoning_effort, revision.supported_reasoning_efforts,
           revision.input_modalities, revision.output_modalities, revision.api_variant_options,
       configured_model.deleted_at, configured_model.created_at, configured_model.updated_at,
       revision.created_at AS revision_created_at
FROM configured_model
JOIN configured_model_revisions revision ON revision.org_id = configured_model.org_id
  AND revision.configured_model_id = configured_model.id
  AND revision.id = configured_model.current_revision_id
`

type RenameConfiguredModelParams struct {
	Name                  string
	OrgID                 uuid.UUID
	ModelProviderConfigID uuid.UUID
	ID                    uuid.UUID
}

type RenameConfiguredModelRow struct {
	ID                        uuid.UUID
	OrgID                     uuid.UUID
	ModelProviderConfigID     uuid.UUID
	ManagementKind            string
	Name                      string
	CurrentRevisionID         uuid.UUID
	ProviderModelSlug         string
	ContextWindowTokens       int32
	MaxOutputTokens           *int32
	DefaultMaxOutputTokens    *int32
	DefaultCacheRetention     *string
	SupportsTools             bool
	SupportsReasoning         bool
	DefaultReasoningEffort    string
	SupportedReasoningEfforts []string
	InputModalities           []string
	OutputModalities          []string
	ApiVariantOptions         json.RawMessage
	DeletedAt                 *time.Time
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	RevisionCreatedAt         time.Time
}

func (q *Queries) RenameConfiguredModel(ctx context.Context, arg RenameConfiguredModelParams) (RenameConfiguredModelRow, error) {
	row := q.db.QueryRow(ctx, renameConfiguredModel,
		arg.Name,
		arg.OrgID,
		arg.ModelProviderConfigID,
		arg.ID,
	)
	var i RenameConfiguredModelRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ModelProviderConfigID,
		&i.ManagementKind,
		&i.Name,
		&i.CurrentRevisionID,
		&i.ProviderModelSlug,
		&i.ContextWindowTokens,
		&i.MaxOutputTokens,
		&i.DefaultMaxOutputTokens,
		&i.DefaultCacheRetention,
		&i.SupportsTools,
		&i.SupportsReasoning,
		&i.DefaultReasoningEffort,
		&i.SupportedReasoningEfforts,
		&i.InputModalities,
		&i.OutputModalities,
		&i.ApiVariantOptions,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevisionCreatedAt,
	)
	return i, err
}

const updateConfiguredModel = `-- name: UpdateConfiguredModel :one
WITH target_configured_model AS (
  SELECT configured_model.id, configured_model.org_id, configured_model.model_provider_config_id
  FROM configured_models configured_model
  JOIN model_provider_configs provider_config ON provider_config.org_id = configured_model.org_id
    AND provider_config.id = configured_model.model_provider_config_id
    AND provider_config.deleted_at IS NULL
  WHERE configured_model.org_id = $1
    AND configured_model.model_provider_config_id = $2
    AND configured_model.id = $3
    AND configured_model.management_kind = $4
    AND configured_model.deleted_at IS NULL
),
revision AS (
  INSERT INTO configured_model_revisions(
    org_id, configured_model_id, model_provider_config_id, provider_model_slug,
    context_window_tokens, max_output_tokens, default_max_output_tokens,
        default_cache_retention, supports_tools, supports_reasoning, default_reasoning_effort,
        supported_reasoning_efforts, input_modalities, output_modalities,
        api_variant_options, created_at
  )
  SELECT target_configured_model.org_id, target_configured_model.id,
         target_configured_model.model_provider_config_id, $5,
         $6, $7,
         $8,
         $9, $10::bool,
         $11::bool, $12::text,
             $13::text[],
             $14::text[], $15::text[],
             $16, statement_timestamp()
  FROM target_configured_model
  RETURNING id, org_id, configured_model_id, model_provider_config_id,
            provider_model_slug, context_window_tokens, max_output_tokens,
            default_max_output_tokens,
                default_cache_retention, supports_tools, supports_reasoning,
                default_reasoning_effort, supported_reasoning_efforts,
                input_modalities, output_modalities, api_variant_options, created_at
),
configured_model AS (
  UPDATE configured_models
  SET name = $17,
      current_revision_id = revision.id,
      updated_at = revision.created_at
  FROM revision
  WHERE configured_models.org_id = revision.org_id
    AND configured_models.id = revision.configured_model_id
  RETURNING configured_models.id, configured_models.org_id,
            configured_models.model_provider_config_id, configured_models.management_kind,
            configured_models.name,
            configured_models.current_revision_id, configured_models.deleted_at,
            configured_models.created_at, configured_models.updated_at
)
SELECT configured_model.id, configured_model.org_id, configured_model.model_provider_config_id,
       configured_model.management_kind, configured_model.name,
       configured_model.current_revision_id, revision.provider_model_slug,
       revision.context_window_tokens, revision.max_output_tokens,
       revision.default_max_output_tokens,
       revision.default_cache_retention, revision.supports_tools, revision.supports_reasoning,
       revision.default_reasoning_effort, revision.supported_reasoning_efforts,
           revision.input_modalities, revision.output_modalities, revision.api_variant_options,
       configured_model.deleted_at, configured_model.created_at, configured_model.updated_at,
       revision.created_at AS revision_created_at
FROM configured_model
JOIN revision ON revision.configured_model_id = configured_model.id
`

type UpdateConfiguredModelParams struct {
	OrgID                     uuid.UUID
	ModelProviderConfigID     uuid.UUID
	ID                        uuid.UUID
	ManagementKind            string
	ProviderModelSlug         string
	ContextWindowTokens       int32
	MaxOutputTokens           *int32
	DefaultMaxOutputTokens    *int32
	DefaultCacheRetention     *string
	SupportsTools             bool
	SupportsReasoning         bool
	DefaultReasoningEffort    string
	SupportedReasoningEfforts []string
	InputModalities           []string
	OutputModalities          []string
	ApiVariantOptions         json.RawMessage
	Name                      string
}

type UpdateConfiguredModelRow struct {
	ID                        uuid.UUID
	OrgID                     uuid.UUID
	ModelProviderConfigID     uuid.UUID
	ManagementKind            string
	Name                      string
	CurrentRevisionID         uuid.UUID
	ProviderModelSlug         string
	ContextWindowTokens       int32
	MaxOutputTokens           *int32
	DefaultMaxOutputTokens    *int32
	DefaultCacheRetention     *string
	SupportsTools             bool
	SupportsReasoning         bool
	DefaultReasoningEffort    string
	SupportedReasoningEfforts []string
	InputModalities           []string
	OutputModalities          []string
	ApiVariantOptions         json.RawMessage
	DeletedAt                 *time.Time
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	RevisionCreatedAt         time.Time
}

func (q *Queries) UpdateConfiguredModel(ctx context.Context, arg UpdateConfiguredModelParams) (UpdateConfiguredModelRow, error) {
	row := q.db.QueryRow(ctx, updateConfiguredModel,
		arg.OrgID,
		arg.ModelProviderConfigID,
		arg.ID,
		arg.ManagementKind,
		arg.ProviderModelSlug,
		arg.ContextWindowTokens,
		arg.MaxOutputTokens,
		arg.DefaultMaxOutputTokens,
		arg.DefaultCacheRetention,
		arg.SupportsTools,
		arg.SupportsReasoning,
		arg.DefaultReasoningEffort,
		arg.SupportedReasoningEfforts,
		arg.InputModalities,
		arg.OutputModalities,
		arg.ApiVariantOptions,
		arg.Name,
	)
	var i UpdateConfiguredModelRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ModelProviderConfigID,
		&i.ManagementKind,
		&i.Name,
		&i.CurrentRevisionID,
		&i.ProviderModelSlug,
		&i.ContextWindowTokens,
		&i.MaxOutputTokens,
		&i.DefaultMaxOutputTokens,
		&i.DefaultCacheRetention,
		&i.SupportsTools,
		&i.SupportsReasoning,
		&i.DefaultReasoningEffort,
		&i.SupportedReasoningEfforts,
		&i.InputModalities,
		&i.OutputModalities,
		&i.ApiVariantOptions,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevisionCreatedAt,
	)
	return i, err
}

const updateModelProviderConfig = `-- name: UpdateModelProviderConfig :one
UPDATE model_provider_configs config
SET base_url = $1,
    endpoint_path = $2,
    request_timeout_ms = $3,
    idle_timeout_ms = $4,
    auth_kind = $5,
    auth_options = $6,
    credential_secret_id = $7,
    updated_at = statement_timestamp()
FROM secrets credential
WHERE config.org_id = $8
  AND config.id = $9
  AND config.deleted_at IS NULL
  AND config.management_kind = $10
  AND credential.org_id = config.org_id
  AND credential.id = $7
  AND credential.deleted_at IS NULL
  AND credential.management_kind = config.management_kind
  AND credential.owner_kind = 'org'
RETURNING config.id, config.org_id, config.management_kind,
          config.name, config.api_format,
          config.api_variant, config.base_url, config.endpoint_path,
          config.request_timeout_ms, config.auth_kind,
          config.auth_options, config.credential_secret_id, config.deleted_at,
          config.created_at, config.updated_at, config.idle_timeout_ms
`

type UpdateModelProviderConfigParams struct {
	BaseUrl            string
	EndpointPath       string
	RequestTimeoutMs   int32
	IdleTimeoutMs      int32
	AuthKind           string
	AuthOptions        json.RawMessage
	CredentialSecretID *uuid.UUID
	OrgID              uuid.UUID
	ID                 uuid.UUID
	ManagementKind     string
}

func (q *Queries) UpdateModelProviderConfig(ctx context.Context, arg UpdateModelProviderConfigParams) (ModelProviderConfig, error) {
	row := q.db.QueryRow(ctx, updateModelProviderConfig,
		arg.BaseUrl,
		arg.EndpointPath,
		arg.RequestTimeoutMs,
		arg.IdleTimeoutMs,
		arg.AuthKind,
		arg.AuthOptions,
		arg.CredentialSecretID,
		arg.OrgID,
		arg.ID,
		arg.ManagementKind,
	)
	var i ModelProviderConfig
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ManagementKind,
		&i.Name,
		&i.ApiFormat,
		&i.ApiVariant,
		&i.BaseUrl,
		&i.EndpointPath,
		&i.RequestTimeoutMs,
		&i.AuthKind,
		&i.AuthOptions,
		&i.CredentialSecretID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdleTimeoutMs,
	)
	return i, err
}

const updateProjectModelGrant = `-- name: UpdateProjectModelGrant :one
UPDATE project_model_grants
SET context_window_tokens = $1,
    max_output_tokens = $2,
    default_max_output_tokens = $3,
    default_cache_retention = $4,
    supports_tools = $5,
    supports_reasoning = $6,
    default_reasoning_effort = $7::text,
    supported_reasoning_efforts = $8::text[],
    input_modalities = $9::text[],
    output_modalities = $10::text[],
    updated_at = statement_timestamp()
WHERE org_id = $11
  AND project_id = $12
  AND id = $13
RETURNING id, org_id, project_id, configured_model_id,
          context_window_tokens, max_output_tokens, default_max_output_tokens,
          default_cache_retention, supports_tools, supports_reasoning,
          default_reasoning_effort, supported_reasoning_efforts,
          input_modalities, output_modalities,
          created_at, updated_at
`

type UpdateProjectModelGrantParams struct {
	ContextWindowTokens       *int32
	MaxOutputTokens           *int32
	DefaultMaxOutputTokens    *int32
	DefaultCacheRetention     *string
	SupportsTools             *bool
	SupportsReasoning         *bool
	DefaultReasoningEffort    string
	SupportedReasoningEfforts []string
	InputModalities           []string
	OutputModalities          []string
	OrgID                     uuid.UUID
	ProjectID                 uuid.UUID
	ID                        uuid.UUID
}

func (q *Queries) UpdateProjectModelGrant(ctx context.Context, arg UpdateProjectModelGrantParams) (ProjectModelGrant, error) {
	row := q.db.QueryRow(ctx, updateProjectModelGrant,
		arg.ContextWindowTokens,
		arg.MaxOutputTokens,
		arg.DefaultMaxOutputTokens,
		arg.DefaultCacheRetention,
		arg.SupportsTools,
		arg.SupportsReasoning,
		arg.DefaultReasoningEffort,
		arg.SupportedReasoningEfforts,
		arg.InputModalities,
		arg.OutputModalities,
		arg.OrgID,
		arg.ProjectID,
		arg.ID,
	)
	var i ProjectModelGrant
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.ConfiguredModelID,
		&i.ContextWindowTokens,
		&i.MaxOutputTokens,
		&i.DefaultMaxOutputTokens,
		&i.DefaultCacheRetention,
		&i.SupportsTools,
		&i.SupportsReasoning,
		&i.DefaultReasoningEffort,
		&i.SupportedReasoningEfforts,
		&i.InputModalities,
		&i.OutputModalities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
