// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: processes.sql

package dbsqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const acceptDaemonProcess = `-- name: AcceptDaemonProcess :one
WITH runtime AS MATERIALIZED (
  SELECT runtime.org_id, runtime.machine_id
  FROM online_daemon_runtimes runtime
  WHERE runtime.id = $3::uuid
    AND runtime.org_id = $4
    AND runtime.machine_id = $5
    AND runtime.daemon_token_id = $6::uuid
)
UPDATE processes process
SET execution_granted_at = statement_timestamp(),
    state = 'starting',
    state_changed_at = statement_timestamp(),
    last_activity_at = statement_timestamp(),
    updated_at = statement_timestamp()
FROM runtime
WHERE process.org_id = runtime.org_id
  AND process.machine_id = runtime.machine_id
  AND process.id = $1
  AND process.state = 'queued'
  AND process.created_at > statement_timestamp() - ($2::int * interval '1 second')
  AND EXISTS (
    SELECT 1
    FROM agent_machine_bindings binding
    JOIN project_machine_grants pmgrant ON pmgrant.project_id = binding.project_id
      AND pmgrant.machine_id = binding.machine_id
    WHERE binding.project_id = process.project_id
      AND binding.agent_id = process.agent_id
      AND binding.id = process.agent_machine_binding_id
      AND binding.machine_id = process.machine_id
      AND binding.state = 'attached'
  )
RETURNING process.id, process.org_id, process.project_id, process.agent_id, process.tool_call_id, process.runtime_lock_id, process.agent_machine_binding_id, process.machine_id, process.execution_granted_at, process.io_mode, process.command, process.shell_selector, process.cwd, process.timeout_seconds, process.initial_wait_ms, process.default_output_cursor, process.state, process.state_reason_code, process.state_reason_message, process.source_started_at, process.source_ended_at, process.state_changed_at, process.exit_code, process.exit_signal, process.created_at, process.updated_at
`

type AcceptDaemonProcessParams struct {
	ProcessID           uuid.UUID
	QueueTimeoutSeconds int32
	DaemonRuntimeID     uuid.UUID
	OrgID               uuid.UUID
	MachineID           uuid.UUID
	DaemonTokenID       uuid.UUID
}

type AcceptDaemonProcessRow struct {
	ID                    uuid.UUID
	OrgID                 uuid.UUID
	ProjectID             uuid.UUID
	AgentID               uuid.UUID
	ToolCallID            uuid.UUID
	RuntimeLockID         uuid.UUID
	AgentMachineBindingID uuid.UUID
	MachineID             uuid.UUID
	ExecutionGrantedAt    *time.Time
	IoMode                string
	Command               string
	ShellSelector         string
	Cwd                   string
	TimeoutSeconds        int32
	InitialWaitMs         int32
	DefaultOutputCursor   int64
	State                 string
	StateReasonCode       *string
	StateReasonMessage    string
	SourceStartedAt       *time.Time
	SourceEndedAt         *time.Time
	StateChangedAt        time.Time
	ExitCode              *int32
	ExitSignal            string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

func (q *Queries) AcceptDaemonProcess(ctx context.Context, arg AcceptDaemonProcessParams) (AcceptDaemonProcessRow, error) {
	row := q.db.QueryRow(ctx, acceptDaemonProcess,
		arg.ProcessID,
		arg.QueueTimeoutSeconds,
		arg.DaemonRuntimeID,
		arg.OrgID,
		arg.MachineID,
		arg.DaemonTokenID,
	)
	var i AcceptDaemonProcessRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.AgentID,
		&i.ToolCallID,
		&i.RuntimeLockID,
		&i.AgentMachineBindingID,
		&i.MachineID,
		&i.ExecutionGrantedAt,
		&i.IoMode,
		&i.Command,
		&i.ShellSelector,
		&i.Cwd,
		&i.TimeoutSeconds,
		&i.InitialWaitMs,
		&i.DefaultOutputCursor,
		&i.State,
		&i.StateReasonCode,
		&i.StateReasonMessage,
		&i.SourceStartedAt,
		&i.SourceEndedAt,
		&i.StateChangedAt,
		&i.ExitCode,
		&i.ExitSignal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const advanceProcessDefaultOutputCursor = `-- name: AdvanceProcessDefaultOutputCursor :execrows
UPDATE processes
SET default_output_cursor = GREATEST(
      default_output_cursor,
      $1::bigint
    )
WHERE project_id = $2
  AND agent_id = $3
  AND id = $4
`

type AdvanceProcessDefaultOutputCursorParams struct {
	NextCursor int64
	ProjectID  uuid.UUID
	AgentID    uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) AdvanceProcessDefaultOutputCursor(ctx context.Context, arg AdvanceProcessDefaultOutputCursorParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceProcessDefaultOutputCursor,
		arg.NextCursor,
		arg.ProjectID,
		arg.AgentID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelUnresolvedProcessesForAgentTurn = `-- name: CancelUnresolvedProcessesForAgentTurn :many
UPDATE processes process
SET state = CASE
      WHEN process.state = 'queued' THEN 'failed'
      ELSE 'unknown'
    END,
    state_reason_code = CASE
      WHEN process.state = 'queued' THEN 'agent_canceled_before_grant'
      ELSE 'agent_canceled_after_grant'
    END,
    state_reason_message = CASE
      WHEN process.state = 'queued' THEN 'agent was canceled before process execution was granted'
      ELSE 'agent was canceled after process execution was granted'
    END,
    state_changed_at = statement_timestamp(),
    last_activity_at = CASE
      WHEN process.state IN ('starting', 'running') THEN statement_timestamp()
      ELSE process.last_activity_at
    END,
    updated_at = statement_timestamp()
FROM tool_call_read_projection tool_call
WHERE process.project_id = $1
  AND process.agent_id = $2
  AND process.state IN ('queued', 'starting', 'running')
  AND process.tool_call_id = tool_call.id
  AND tool_call.project_id = process.project_id
  AND tool_call.agent_id = process.agent_id
  AND tool_call.state = 'waiting'
  AND tool_call.turn_id = $3
RETURNING process.id, process.org_id, process.machine_id, process.state
`

type CancelUnresolvedProcessesForAgentTurnParams struct {
	ProjectID uuid.UUID
	AgentID   uuid.UUID
	TurnID    uuid.UUID
}

type CancelUnresolvedProcessesForAgentTurnRow struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	MachineID uuid.UUID
	State     string
}

func (q *Queries) CancelUnresolvedProcessesForAgentTurn(ctx context.Context, arg CancelUnresolvedProcessesForAgentTurnParams) ([]CancelUnresolvedProcessesForAgentTurnRow, error) {
	rows, err := q.db.Query(ctx, cancelUnresolvedProcessesForAgentTurn, arg.ProjectID, arg.AgentID, arg.TurnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CancelUnresolvedProcessesForAgentTurnRow{}
	for rows.Next() {
		var i CancelUnresolvedProcessesForAgentTurnRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.MachineID,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeDaemonObservedProcess = `-- name: CompleteDaemonObservedProcess :one
UPDATE processes process
SET state = $1,
    source_started_at = coalesce(source_started_at, $2::timestamptz),
    source_ended_at = CASE
      WHEN $3::boolean
        AND process.source_started_at IS NOT NULL
        AND $4::timestamptz IS NULL
      THEN greatest(process.source_started_at, statement_timestamp())
      WHEN $4::timestamptz IS NULL THEN NULL
      ELSE greatest(process.source_started_at, $4::timestamptz)
    END,
    exit_code = $5,
    exit_signal = $6,
    state_reason_code = $7,
    state_reason_message = $8,
    state_changed_at = statement_timestamp(),
    last_activity_at = statement_timestamp(),
    updated_at = statement_timestamp()
WHERE process.project_id = $9
  AND process.agent_id = $10
  AND process.id = $11
  AND process.machine_id = $12
  AND (
    process.state IN ('starting', 'running')
    OR (
      $3::boolean
      AND process.state = 'queued'
      AND process.execution_granted_at IS NULL
    )
  )
  AND $1::text IN ('exited', 'failed', 'killed', 'unknown')
  AND ($1::text <> 'exited' OR $5::integer IS NOT NULL)
  AND ($1::text IN ('exited', 'failed') OR $5::integer IS NULL)
  AND ($1::text <> 'failed' OR $7::text IS NOT NULL)
  AND ($1::text <> 'unknown' OR $7::text IS NOT NULL)
  AND (
    $2::timestamptz IS NULL
    OR process.source_started_at IS NULL
    OR process.source_started_at = $2::timestamptz
  )
  AND (
    $4::timestamptz IS NULL
    OR coalesce(process.source_started_at, $2::timestamptz) IS NULL
    OR $3::boolean
    OR $4::timestamptz >= coalesce(process.source_started_at, $2::timestamptz)
  )
  AND (
    $1::text NOT IN ('exited', 'killed')
    OR $4::timestamptz IS NOT NULL
  )
  AND (
    $1::text <> 'failed'
    OR $3::boolean
    OR coalesce(process.source_started_at, $2::timestamptz) IS NULL
    OR $4::timestamptz IS NOT NULL
  )
RETURNING process.id, process.org_id, process.project_id, process.agent_id, process.tool_call_id, process.runtime_lock_id, process.agent_machine_binding_id, process.machine_id, process.execution_granted_at, process.io_mode, process.command, process.shell_selector, process.cwd, process.env, process.secret_env, process.timeout_seconds, process.initial_wait_ms, process.default_output_cursor, process.state, process.state_reason_code, process.state_reason_message, process.source_started_at, process.source_ended_at, process.state_changed_at, process.exit_code, process.exit_signal, process.created_at, process.updated_at, process.last_activity_at
`

type CompleteDaemonObservedProcessParams struct {
	State              string
	SourceStartedAt    *time.Time
	StorageExhausted   bool
	SourceEndedAt      *time.Time
	ExitCode           *int32
	ExitSignal         string
	StateReasonCode    *string
	StateReasonMessage string
	ProjectID          uuid.UUID
	AgentID            uuid.UUID
	ID                 uuid.UUID
	MachineID          uuid.UUID
}

func (q *Queries) CompleteDaemonObservedProcess(ctx context.Context, arg CompleteDaemonObservedProcessParams) (Process, error) {
	row := q.db.QueryRow(ctx, completeDaemonObservedProcess,
		arg.State,
		arg.SourceStartedAt,
		arg.StorageExhausted,
		arg.SourceEndedAt,
		arg.ExitCode,
		arg.ExitSignal,
		arg.StateReasonCode,
		arg.StateReasonMessage,
		arg.ProjectID,
		arg.AgentID,
		arg.ID,
		arg.MachineID,
	)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.AgentID,
		&i.ToolCallID,
		&i.RuntimeLockID,
		&i.AgentMachineBindingID,
		&i.MachineID,
		&i.ExecutionGrantedAt,
		&i.IoMode,
		&i.Command,
		&i.ShellSelector,
		&i.Cwd,
		&i.Env,
		&i.SecretEnv,
		&i.TimeoutSeconds,
		&i.InitialWaitMs,
		&i.DefaultOutputCursor,
		&i.State,
		&i.StateReasonCode,
		&i.StateReasonMessage,
		&i.SourceStartedAt,
		&i.SourceEndedAt,
		&i.StateChangedAt,
		&i.ExitCode,
		&i.ExitSignal,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActivityAt,
	)
	return i, err
}

const completeProcess = `-- name: CompleteProcess :one
UPDATE processes
SET state = $1,
    source_ended_at = $2::timestamptz,
    exit_code = $3,
    exit_signal = $4,
    state_reason_code = $5,
    state_reason_message = $6,
    state_changed_at = statement_timestamp(),
    last_activity_at = statement_timestamp(),
    updated_at = statement_timestamp()
WHERE project_id = $7
  AND agent_id = $8
  AND id = $9
  AND runtime_lock_id = $10
  AND state IN ('starting', 'running')
RETURNING id, org_id, project_id, agent_id, tool_call_id, runtime_lock_id, agent_machine_binding_id, machine_id, execution_granted_at, io_mode, command, shell_selector, cwd, env, secret_env, timeout_seconds, initial_wait_ms, default_output_cursor, state, state_reason_code, state_reason_message, source_started_at, source_ended_at, state_changed_at, exit_code, exit_signal, created_at, updated_at, last_activity_at
`

type CompleteProcessParams struct {
	State              string
	SourceEndedAt      time.Time
	ExitCode           *int32
	ExitSignal         string
	StateReasonCode    *string
	StateReasonMessage string
	ProjectID          uuid.UUID
	AgentID            uuid.UUID
	ID                 uuid.UUID
	RuntimeLockID      uuid.UUID
}

func (q *Queries) CompleteProcess(ctx context.Context, arg CompleteProcessParams) (Process, error) {
	row := q.db.QueryRow(ctx, completeProcess,
		arg.State,
		arg.SourceEndedAt,
		arg.ExitCode,
		arg.ExitSignal,
		arg.StateReasonCode,
		arg.StateReasonMessage,
		arg.ProjectID,
		arg.AgentID,
		arg.ID,
		arg.RuntimeLockID,
	)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.AgentID,
		&i.ToolCallID,
		&i.RuntimeLockID,
		&i.AgentMachineBindingID,
		&i.MachineID,
		&i.ExecutionGrantedAt,
		&i.IoMode,
		&i.Command,
		&i.ShellSelector,
		&i.Cwd,
		&i.Env,
		&i.SecretEnv,
		&i.TimeoutSeconds,
		&i.InitialWaitMs,
		&i.DefaultOutputCursor,
		&i.State,
		&i.StateReasonCode,
		&i.StateReasonMessage,
		&i.SourceStartedAt,
		&i.SourceEndedAt,
		&i.StateChangedAt,
		&i.ExitCode,
		&i.ExitSignal,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActivityAt,
	)
	return i, err
}

const countNonTerminalProcessesForAgent = `-- name: CountNonTerminalProcessesForAgent :one
SELECT count(*)::bigint
FROM processes
WHERE project_id = $1
  AND agent_id = $2
  AND state IN ('queued', 'starting', 'running')
`

type CountNonTerminalProcessesForAgentParams struct {
	ProjectID uuid.UUID
	AgentID   uuid.UUID
}

func (q *Queries) CountNonTerminalProcessesForAgent(ctx context.Context, arg CountNonTerminalProcessesForAgentParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNonTerminalProcessesForAgent, arg.ProjectID, arg.AgentID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const failProcessBeforeExecution = `-- name: FailProcessBeforeExecution :one
UPDATE processes process
SET state = 'failed',
    state_reason_code = $1,
    state_reason_message = $2,
    state_changed_at = statement_timestamp(),
    last_activity_at = statement_timestamp(),
    updated_at = statement_timestamp()
WHERE process.org_id = $3
  AND process.machine_id = $4
  AND process.id = $5
  AND process.state = 'starting'
  AND process.source_started_at IS NULL
RETURNING process.id, process.org_id, process.project_id, process.agent_id, process.tool_call_id, process.runtime_lock_id, process.agent_machine_binding_id, process.machine_id, process.execution_granted_at, process.io_mode, process.command, process.shell_selector, process.cwd, process.env, process.secret_env, process.timeout_seconds, process.initial_wait_ms, process.default_output_cursor, process.state, process.state_reason_code, process.state_reason_message, process.source_started_at, process.source_ended_at, process.state_changed_at, process.exit_code, process.exit_signal, process.created_at, process.updated_at, process.last_activity_at
`

type FailProcessBeforeExecutionParams struct {
	StateReasonCode    *string
	StateReasonMessage string
	OrgID              uuid.UUID
	MachineID          uuid.UUID
	ID                 uuid.UUID
}

func (q *Queries) FailProcessBeforeExecution(ctx context.Context, arg FailProcessBeforeExecutionParams) (Process, error) {
	row := q.db.QueryRow(ctx, failProcessBeforeExecution,
		arg.StateReasonCode,
		arg.StateReasonMessage,
		arg.OrgID,
		arg.MachineID,
		arg.ID,
	)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.AgentID,
		&i.ToolCallID,
		&i.RuntimeLockID,
		&i.AgentMachineBindingID,
		&i.MachineID,
		&i.ExecutionGrantedAt,
		&i.IoMode,
		&i.Command,
		&i.ShellSelector,
		&i.Cwd,
		&i.Env,
		&i.SecretEnv,
		&i.TimeoutSeconds,
		&i.InitialWaitMs,
		&i.DefaultOutputCursor,
		&i.State,
		&i.StateReasonCode,
		&i.StateReasonMessage,
		&i.SourceStartedAt,
		&i.SourceEndedAt,
		&i.StateChangedAt,
		&i.ExitCode,
		&i.ExitSignal,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActivityAt,
	)
	return i, err
}

const getDaemonArtifactProcessScope = `-- name: GetDaemonArtifactProcessScope :one
SELECT process.project_id,
       process.agent_id,
       tool_call.name AS tool_name,
       COALESCE(tool_call.input->>'artifact_id', tool_call.input->>'path', '')::text AS artifact_locator
FROM processes process
JOIN tool_calls tool_call ON tool_call.agent_id = process.agent_id
  AND tool_call.id = process.tool_call_id
WHERE process.org_id = $1
  AND process.machine_id = $2
  AND process.tool_call_id = $3
  AND process.execution_granted_at IS NOT NULL
  AND process.state IN ('starting', 'running')
  AND tool_call.type = 'built_in'
  AND tool_call.name = ANY($4::text[])
`

type GetDaemonArtifactProcessScopeParams struct {
	OrgID      uuid.UUID
	MachineID  uuid.UUID
	ToolCallID uuid.UUID
	ToolNames  []string
}

type GetDaemonArtifactProcessScopeRow struct {
	ProjectID       uuid.UUID
	AgentID         uuid.UUID
	ToolName        string
	ArtifactLocator string
}

func (q *Queries) GetDaemonArtifactProcessScope(ctx context.Context, arg GetDaemonArtifactProcessScopeParams) (GetDaemonArtifactProcessScopeRow, error) {
	row := q.db.QueryRow(ctx, getDaemonArtifactProcessScope,
		arg.OrgID,
		arg.MachineID,
		arg.ToolCallID,
		arg.ToolNames,
	)
	var i GetDaemonArtifactProcessScopeRow
	err := row.Scan(
		&i.ProjectID,
		&i.AgentID,
		&i.ToolName,
		&i.ArtifactLocator,
	)
	return i, err
}

const getDaemonProcessForMachineReport = `-- name: GetDaemonProcessForMachineReport :one
SELECT process.id, process.org_id, process.project_id, process.agent_id, process.tool_call_id, process.runtime_lock_id, process.agent_machine_binding_id, process.machine_id, process.execution_granted_at, process.io_mode, process.command, process.shell_selector, process.cwd, process.env, process.secret_env, process.timeout_seconds, process.initial_wait_ms, process.default_output_cursor, process.state, process.state_reason_code, process.state_reason_message, process.source_started_at, process.source_ended_at, process.state_changed_at, process.exit_code, process.exit_signal, process.created_at, process.updated_at, process.last_activity_at
FROM processes process
JOIN reportable_daemon_runtimes runtime ON runtime.org_id = process.org_id
  AND runtime.machine_id = process.machine_id
WHERE process.org_id = $1
  AND process.machine_id = $2
  AND runtime.id = $3
  AND runtime.daemon_token_id = $4
  AND process.id = $5
`

type GetDaemonProcessForMachineReportParams struct {
	OrgID           uuid.UUID
	MachineID       uuid.UUID
	DaemonRuntimeID uuid.UUID
	DaemonTokenID   uuid.UUID
	ID              uuid.UUID
}

func (q *Queries) GetDaemonProcessForMachineReport(ctx context.Context, arg GetDaemonProcessForMachineReportParams) (Process, error) {
	row := q.db.QueryRow(ctx, getDaemonProcessForMachineReport,
		arg.OrgID,
		arg.MachineID,
		arg.DaemonRuntimeID,
		arg.DaemonTokenID,
		arg.ID,
	)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.AgentID,
		&i.ToolCallID,
		&i.RuntimeLockID,
		&i.AgentMachineBindingID,
		&i.MachineID,
		&i.ExecutionGrantedAt,
		&i.IoMode,
		&i.Command,
		&i.ShellSelector,
		&i.Cwd,
		&i.Env,
		&i.SecretEnv,
		&i.TimeoutSeconds,
		&i.InitialWaitMs,
		&i.DefaultOutputCursor,
		&i.State,
		&i.StateReasonCode,
		&i.StateReasonMessage,
		&i.SourceStartedAt,
		&i.SourceEndedAt,
		&i.StateChangedAt,
		&i.ExitCode,
		&i.ExitSignal,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActivityAt,
	)
	return i, err
}

const getDaemonProcessForProjectReport = `-- name: GetDaemonProcessForProjectReport :one
SELECT processes.id, processes.org_id, processes.project_id, processes.agent_id, processes.tool_call_id, processes.runtime_lock_id, processes.agent_machine_binding_id, processes.machine_id, processes.execution_granted_at, processes.io_mode, processes.command, processes.shell_selector, processes.cwd, processes.env, processes.secret_env, processes.timeout_seconds, processes.initial_wait_ms, processes.default_output_cursor, processes.state, processes.state_reason_code, processes.state_reason_message, processes.source_started_at, processes.source_ended_at, processes.state_changed_at, processes.exit_code, processes.exit_signal, processes.created_at, processes.updated_at, processes.last_activity_at
FROM processes
WHERE processes.project_id = $1
  AND processes.machine_id = $2
  AND processes.id = $3
`

type GetDaemonProcessForProjectReportParams struct {
	ProjectID uuid.UUID
	MachineID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetDaemonProcessForProjectReport(ctx context.Context, arg GetDaemonProcessForProjectReportParams) (Process, error) {
	row := q.db.QueryRow(ctx, getDaemonProcessForProjectReport, arg.ProjectID, arg.MachineID, arg.ID)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.AgentID,
		&i.ToolCallID,
		&i.RuntimeLockID,
		&i.AgentMachineBindingID,
		&i.MachineID,
		&i.ExecutionGrantedAt,
		&i.IoMode,
		&i.Command,
		&i.ShellSelector,
		&i.Cwd,
		&i.Env,
		&i.SecretEnv,
		&i.TimeoutSeconds,
		&i.InitialWaitMs,
		&i.DefaultOutputCursor,
		&i.State,
		&i.StateReasonCode,
		&i.StateReasonMessage,
		&i.SourceStartedAt,
		&i.SourceEndedAt,
		&i.StateChangedAt,
		&i.ExitCode,
		&i.ExitSignal,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActivityAt,
	)
	return i, err
}

const getProcess = `-- name: GetProcess :one
SELECT id, org_id, project_id, agent_id, tool_call_id, runtime_lock_id, agent_machine_binding_id, machine_id, execution_granted_at, io_mode, command, shell_selector, cwd, env, secret_env, timeout_seconds, initial_wait_ms, default_output_cursor, state, state_reason_code, state_reason_message, source_started_at, source_ended_at, state_changed_at, exit_code, exit_signal, created_at, updated_at, last_activity_at
FROM processes
WHERE project_id = $1
  AND agent_id = $2
  AND id = $3
`

type GetProcessParams struct {
	ProjectID uuid.UUID
	AgentID   uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetProcess(ctx context.Context, arg GetProcessParams) (Process, error) {
	row := q.db.QueryRow(ctx, getProcess, arg.ProjectID, arg.AgentID, arg.ID)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.AgentID,
		&i.ToolCallID,
		&i.RuntimeLockID,
		&i.AgentMachineBindingID,
		&i.MachineID,
		&i.ExecutionGrantedAt,
		&i.IoMode,
		&i.Command,
		&i.ShellSelector,
		&i.Cwd,
		&i.Env,
		&i.SecretEnv,
		&i.TimeoutSeconds,
		&i.InitialWaitMs,
		&i.DefaultOutputCursor,
		&i.State,
		&i.StateReasonCode,
		&i.StateReasonMessage,
		&i.SourceStartedAt,
		&i.SourceEndedAt,
		&i.StateChangedAt,
		&i.ExitCode,
		&i.ExitSignal,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActivityAt,
	)
	return i, err
}

const getProcessByMachine = `-- name: GetProcessByMachine :one
SELECT id, org_id, project_id, agent_id, tool_call_id, runtime_lock_id, agent_machine_binding_id, machine_id, execution_granted_at, io_mode, command, shell_selector, cwd, env, secret_env, timeout_seconds, initial_wait_ms, default_output_cursor, state, state_reason_code, state_reason_message, source_started_at, source_ended_at, state_changed_at, exit_code, exit_signal, created_at, updated_at, last_activity_at
FROM processes
WHERE org_id = $1
  AND machine_id = $2
  AND id = $3
`

type GetProcessByMachineParams struct {
	OrgID     uuid.UUID
	MachineID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetProcessByMachine(ctx context.Context, arg GetProcessByMachineParams) (Process, error) {
	row := q.db.QueryRow(ctx, getProcessByMachine, arg.OrgID, arg.MachineID, arg.ID)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.AgentID,
		&i.ToolCallID,
		&i.RuntimeLockID,
		&i.AgentMachineBindingID,
		&i.MachineID,
		&i.ExecutionGrantedAt,
		&i.IoMode,
		&i.Command,
		&i.ShellSelector,
		&i.Cwd,
		&i.Env,
		&i.SecretEnv,
		&i.TimeoutSeconds,
		&i.InitialWaitMs,
		&i.DefaultOutputCursor,
		&i.State,
		&i.StateReasonCode,
		&i.StateReasonMessage,
		&i.SourceStartedAt,
		&i.SourceEndedAt,
		&i.StateChangedAt,
		&i.ExitCode,
		&i.ExitSignal,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActivityAt,
	)
	return i, err
}

const getProcessByToolCall = `-- name: GetProcessByToolCall :one
SELECT id, org_id, project_id, agent_id, tool_call_id, runtime_lock_id, agent_machine_binding_id, machine_id, execution_granted_at, io_mode, command, shell_selector, cwd, env, secret_env, timeout_seconds, initial_wait_ms, default_output_cursor, state, state_reason_code, state_reason_message, source_started_at, source_ended_at, state_changed_at, exit_code, exit_signal, created_at, updated_at, last_activity_at
FROM processes
WHERE project_id = $1
  AND agent_id = $2
  AND tool_call_id = $3
`

type GetProcessByToolCallParams struct {
	ProjectID  uuid.UUID
	AgentID    uuid.UUID
	ToolCallID uuid.UUID
}

func (q *Queries) GetProcessByToolCall(ctx context.Context, arg GetProcessByToolCallParams) (Process, error) {
	row := q.db.QueryRow(ctx, getProcessByToolCall, arg.ProjectID, arg.AgentID, arg.ToolCallID)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.AgentID,
		&i.ToolCallID,
		&i.RuntimeLockID,
		&i.AgentMachineBindingID,
		&i.MachineID,
		&i.ExecutionGrantedAt,
		&i.IoMode,
		&i.Command,
		&i.ShellSelector,
		&i.Cwd,
		&i.Env,
		&i.SecretEnv,
		&i.TimeoutSeconds,
		&i.InitialWaitMs,
		&i.DefaultOutputCursor,
		&i.State,
		&i.StateReasonCode,
		&i.StateReasonMessage,
		&i.SourceStartedAt,
		&i.SourceEndedAt,
		&i.StateChangedAt,
		&i.ExitCode,
		&i.ExitSignal,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActivityAt,
	)
	return i, err
}

const getProcessExecutionConfig = `-- name: GetProcessExecutionConfig :one
SELECT binding.id AS binding_id,
       binding.org_id,
       binding.project_id,
       binding.machine_id,
       binding.cwd AS binding_cwd,
       binding.env_overlay AS binding_env_overlay,
       binding.secret_env_overlay AS binding_secret_env_overlay,
       machine.cwd AS machine_cwd,
       machine.env AS machine_env,
       machine.secret_env AS machine_secret_env,
       CASE
           WHEN machine.source_kind = 'pool' AND pool.management_kind = 'cluster'
               THEN COALESCE(admission.new_managed_work_allowed, true)
           ELSE true
       END AS new_managed_work_allowed
FROM agent_machine_bindings binding
JOIN machines machine ON machine.org_id = binding.org_id
  AND machine.id = binding.machine_id
LEFT JOIN machine_pools pool ON pool.org_id = machine.org_id
  AND pool.id = machine.machine_pool_id
LEFT JOIN org_managed_work_admission admission ON admission.org_id = binding.org_id
WHERE binding.project_id = $1
  AND binding.agent_id = $2
  AND binding.id = $3
`

type GetProcessExecutionConfigParams struct {
	ProjectID             uuid.UUID
	AgentID               uuid.UUID
	AgentMachineBindingID uuid.UUID
}

type GetProcessExecutionConfigRow struct {
	BindingID               uuid.UUID
	OrgID                   uuid.UUID
	ProjectID               uuid.UUID
	MachineID               uuid.UUID
	BindingCwd              string
	BindingEnvOverlay       json.RawMessage
	BindingSecretEnvOverlay json.RawMessage
	MachineCwd              string
	MachineEnv              json.RawMessage
	MachineSecretEnv        json.RawMessage
	NewManagedWorkAllowed   bool
}

// @sqlc-vet-disable machines-deleted-at
// @sqlc-vet-disable machine-pools-deleted-at
// Binding attachment governs liveness; machine env still resolves during teardown.
func (q *Queries) GetProcessExecutionConfig(ctx context.Context, arg GetProcessExecutionConfigParams) (GetProcessExecutionConfigRow, error) {
	row := q.db.QueryRow(ctx, getProcessExecutionConfig, arg.ProjectID, arg.AgentID, arg.AgentMachineBindingID)
	var i GetProcessExecutionConfigRow
	err := row.Scan(
		&i.BindingID,
		&i.OrgID,
		&i.ProjectID,
		&i.MachineID,
		&i.BindingCwd,
		&i.BindingEnvOverlay,
		&i.BindingSecretEnvOverlay,
		&i.MachineCwd,
		&i.MachineEnv,
		&i.MachineSecretEnv,
		&i.NewManagedWorkAllowed,
	)
	return i, err
}

const getProcessForUpdate = `-- name: GetProcessForUpdate :one
SELECT id, org_id, project_id, agent_id, tool_call_id, runtime_lock_id, agent_machine_binding_id, machine_id, execution_granted_at, io_mode, command, shell_selector, cwd, env, secret_env, timeout_seconds, initial_wait_ms, default_output_cursor, state, state_reason_code, state_reason_message, source_started_at, source_ended_at, state_changed_at, exit_code, exit_signal, created_at, updated_at, last_activity_at
FROM processes
WHERE project_id = $1
  AND agent_id = $2
  AND id = $3
FOR UPDATE
`

type GetProcessForUpdateParams struct {
	ProjectID uuid.UUID
	AgentID   uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetProcessForUpdate(ctx context.Context, arg GetProcessForUpdateParams) (Process, error) {
	row := q.db.QueryRow(ctx, getProcessForUpdate, arg.ProjectID, arg.AgentID, arg.ID)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.AgentID,
		&i.ToolCallID,
		&i.RuntimeLockID,
		&i.AgentMachineBindingID,
		&i.MachineID,
		&i.ExecutionGrantedAt,
		&i.IoMode,
		&i.Command,
		&i.ShellSelector,
		&i.Cwd,
		&i.Env,
		&i.SecretEnv,
		&i.TimeoutSeconds,
		&i.InitialWaitMs,
		&i.DefaultOutputCursor,
		&i.State,
		&i.StateReasonCode,
		&i.StateReasonMessage,
		&i.SourceStartedAt,
		&i.SourceEndedAt,
		&i.StateChangedAt,
		&i.ExitCode,
		&i.ExitSignal,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActivityAt,
	)
	return i, err
}

const insertProcess = `-- name: InsertProcess :one
WITH target_agent AS MATERIALIZED (
  SELECT agent.org_id, agent.project_id, agent.id
  FROM agents agent
  WHERE agent.project_id = $11
    AND agent.id = $12
),
live_runtime AS MATERIALIZED (
  SELECT agent.project_id, runtime_lock.agent_id, runtime_lock.id
  FROM agent_runtime_locks runtime_lock
  JOIN agents agent ON agent.id = runtime_lock.agent_id
  WHERE agent.project_id = $11
    AND runtime_lock.agent_id = $12
    AND runtime_lock.id = $13
    AND runtime_lock.cancel_requested_at IS NULL
    AND runtime_lock.lease_expires_at > statement_timestamp()
),
bound_machine AS MATERIALIZED (
  SELECT binding.machine_id
  FROM agent_machine_bindings binding
  WHERE binding.project_id = $11
    AND binding.agent_id = $12
    AND binding.id = $10
    AND binding.state = 'attached'
),
reachable_machine AS MATERIALIZED (
  SELECT bound.machine_id
  FROM bound_machine bound
  JOIN machine_connection_states connection ON connection.org_id = (SELECT org_id FROM target_agent)
    AND connection.machine_id = bound.machine_id
  WHERE connection.connection_state IN ('online', 'asleep')
)
INSERT INTO processes(org_id, project_id, agent_id, tool_call_id, runtime_lock_id, agent_machine_binding_id, machine_id, execution_granted_at, io_mode, command, shell_selector, cwd, env, secret_env, timeout_seconds, initial_wait_ms, state, state_changed_at, created_at, updated_at)
SELECT agent.org_id, agent.project_id, agent.id, tool_call.id, runtime_lock.id, binding.id, binding.machine_id, NULL, $1, $2, $3, $4, $5::jsonb, $6::jsonb, $7, $8, 'queued', statement_timestamp(), statement_timestamp(), statement_timestamp()
FROM target_agent agent
JOIN live_runtime runtime_lock ON runtime_lock.project_id = agent.project_id
  AND runtime_lock.agent_id = agent.id
JOIN tool_calls tool_call ON tool_call.agent_id = agent.id
  AND tool_call.id = $9
JOIN agent_machine_bindings binding ON binding.project_id = agent.project_id
  AND binding.agent_id = agent.id
  AND binding.id = $10
  AND binding.state = 'attached'
JOIN project_machine_grants pmgrant ON pmgrant.project_id = binding.project_id
  AND pmgrant.machine_id = binding.machine_id
JOIN reachable_machine ON true
ON CONFLICT (agent_id, tool_call_id) DO NOTHING
RETURNING id, org_id, project_id, agent_id, tool_call_id, runtime_lock_id, agent_machine_binding_id, machine_id, execution_granted_at, io_mode, command, shell_selector, cwd, env, secret_env, timeout_seconds, initial_wait_ms, default_output_cursor, state, state_reason_code, state_reason_message, source_started_at, source_ended_at, state_changed_at, exit_code, exit_signal, created_at, updated_at, last_activity_at
`

type InsertProcessParams struct {
	IoMode                string
	Command               string
	ShellSelector         string
	Cwd                   string
	Env                   json.RawMessage
	SecretEnv             json.RawMessage
	TimeoutSeconds        int32
	InitialWaitMs         int32
	ToolCallID            uuid.UUID
	AgentMachineBindingID uuid.UUID
	ProjectID             uuid.UUID
	AgentID               uuid.UUID
	RuntimeLockID         uuid.UUID
}

func (q *Queries) InsertProcess(ctx context.Context, arg InsertProcessParams) (Process, error) {
	row := q.db.QueryRow(ctx, insertProcess,
		arg.IoMode,
		arg.Command,
		arg.ShellSelector,
		arg.Cwd,
		arg.Env,
		arg.SecretEnv,
		arg.TimeoutSeconds,
		arg.InitialWaitMs,
		arg.ToolCallID,
		arg.AgentMachineBindingID,
		arg.ProjectID,
		arg.AgentID,
		arg.RuntimeLockID,
	)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.AgentID,
		&i.ToolCallID,
		&i.RuntimeLockID,
		&i.AgentMachineBindingID,
		&i.MachineID,
		&i.ExecutionGrantedAt,
		&i.IoMode,
		&i.Command,
		&i.ShellSelector,
		&i.Cwd,
		&i.Env,
		&i.SecretEnv,
		&i.TimeoutSeconds,
		&i.InitialWaitMs,
		&i.DefaultOutputCursor,
		&i.State,
		&i.StateReasonCode,
		&i.StateReasonMessage,
		&i.SourceStartedAt,
		&i.SourceEndedAt,
		&i.StateChangedAt,
		&i.ExitCode,
		&i.ExitSignal,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActivityAt,
	)
	return i, err
}

const listActiveProcesses = `-- name: ListActiveProcesses :many
SELECT id, state, machine_id, io_mode, command, shell_selector, cwd, source_started_at, created_at, updated_at, tool_call_id
FROM processes
WHERE project_id = $1
  AND agent_id = $2
  AND state IN ('starting', 'running')
ORDER BY updated_at DESC, id
LIMIT 20
`

type ListActiveProcessesParams struct {
	ProjectID uuid.UUID
	AgentID   uuid.UUID
}

type ListActiveProcessesRow struct {
	ID              uuid.UUID
	State           string
	MachineID       uuid.UUID
	IoMode          string
	Command         string
	ShellSelector   string
	Cwd             string
	SourceStartedAt *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
	ToolCallID      uuid.UUID
}

func (q *Queries) ListActiveProcesses(ctx context.Context, arg ListActiveProcessesParams) ([]ListActiveProcessesRow, error) {
	rows, err := q.db.Query(ctx, listActiveProcesses, arg.ProjectID, arg.AgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveProcessesRow{}
	for rows.Next() {
		var i ListActiveProcessesRow
		if err := rows.Scan(
			&i.ID,
			&i.State,
			&i.MachineID,
			&i.IoMode,
			&i.Command,
			&i.ShellSelector,
			&i.Cwd,
			&i.SourceStartedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ToolCallID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDaemonProcessOffers = `-- name: ListDaemonProcessOffers :many
WITH runtime AS MATERIALIZED (
  SELECT runtime.org_id, runtime.machine_id
  FROM online_daemon_runtimes runtime
  WHERE runtime.id = $5::uuid
    AND runtime.org_id = $1
    AND runtime.machine_id = $2
    AND runtime.daemon_token_id = $6::uuid
)
SELECT process.id, process.org_id, process.project_id, process.agent_id, process.tool_call_id, process.runtime_lock_id, process.agent_machine_binding_id, process.machine_id, process.execution_granted_at, process.io_mode, process.command, process.shell_selector, process.cwd, process.env, process.secret_env, process.timeout_seconds, process.initial_wait_ms, process.default_output_cursor, process.state, process.state_reason_code, process.state_reason_message, process.source_started_at, process.source_ended_at, process.state_changed_at, process.exit_code, process.exit_signal, process.created_at, process.updated_at, process.last_activity_at
FROM processes process
JOIN runtime ON runtime.org_id = process.org_id
  AND runtime.machine_id = process.machine_id
JOIN agent_machine_bindings binding ON binding.project_id = process.project_id
  AND binding.agent_id = process.agent_id
  AND binding.id = process.agent_machine_binding_id
  AND binding.machine_id = process.machine_id
  AND binding.state = 'attached'
JOIN project_machine_grants pmgrant ON pmgrant.project_id = binding.project_id
  AND pmgrant.machine_id = binding.machine_id
WHERE process.org_id = $1
  AND process.machine_id = $2
  AND process.state = 'queued'
  AND process.created_at > statement_timestamp() - ($3::int * interval '1 second')
ORDER BY process.created_at, process.id
LIMIT $4
`

type ListDaemonProcessOffersParams struct {
	OrgID               uuid.UUID
	MachineID           uuid.UUID
	QueueTimeoutSeconds int32
	LimitCount          int32
	DaemonRuntimeID     uuid.UUID
	DaemonTokenID       uuid.UUID
}

func (q *Queries) ListDaemonProcessOffers(ctx context.Context, arg ListDaemonProcessOffersParams) ([]Process, error) {
	rows, err := q.db.Query(ctx, listDaemonProcessOffers,
		arg.OrgID,
		arg.MachineID,
		arg.QueueTimeoutSeconds,
		arg.LimitCount,
		arg.DaemonRuntimeID,
		arg.DaemonTokenID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Process{}
	for rows.Next() {
		var i Process
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.AgentID,
			&i.ToolCallID,
			&i.RuntimeLockID,
			&i.AgentMachineBindingID,
			&i.MachineID,
			&i.ExecutionGrantedAt,
			&i.IoMode,
			&i.Command,
			&i.ShellSelector,
			&i.Cwd,
			&i.Env,
			&i.SecretEnv,
			&i.TimeoutSeconds,
			&i.InitialWaitMs,
			&i.DefaultOutputCursor,
			&i.State,
			&i.StateReasonCode,
			&i.StateReasonMessage,
			&i.SourceStartedAt,
			&i.SourceEndedAt,
			&i.StateChangedAt,
			&i.ExitCode,
			&i.ExitSignal,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMachineLifecycleTerminalAgentRefs = `-- name: ListMachineLifecycleTerminalAgentRefs :many
SELECT DISTINCT process.project_id, process.agent_id
FROM processes process
WHERE process.org_id = $1
  AND process.machine_id = $2
  AND (
    process.state IN ('starting', 'running')
    OR EXISTS (
      SELECT 1
      FROM process_actions action
      WHERE action.project_id = process.project_id
        AND action.agent_id = process.agent_id
        AND action.process_id = process.id
        AND action.state IN ('queued', 'accepted')
    )
    OR (
      process.state = 'queued'
      AND process.tool_call_id IS NOT NULL
      AND EXISTS (
        SELECT 1
        FROM tool_calls tool_call
        WHERE tool_call.agent_id = process.agent_id
          AND tool_call.id = process.tool_call_id
          AND tool_call.type = 'built_in'
          AND tool_call.state = 'waiting'
      )
    )
  )
ORDER BY process.project_id, process.agent_id
`

type ListMachineLifecycleTerminalAgentRefsParams struct {
	OrgID     uuid.UUID
	MachineID uuid.UUID
}

type ListMachineLifecycleTerminalAgentRefsRow struct {
	ProjectID uuid.UUID
	AgentID   uuid.UUID
}

func (q *Queries) ListMachineLifecycleTerminalAgentRefs(ctx context.Context, arg ListMachineLifecycleTerminalAgentRefsParams) ([]ListMachineLifecycleTerminalAgentRefsRow, error) {
	rows, err := q.db.Query(ctx, listMachineLifecycleTerminalAgentRefs, arg.OrgID, arg.MachineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMachineLifecycleTerminalAgentRefsRow{}
	for rows.Next() {
		var i ListMachineLifecycleTerminalAgentRefsRow
		if err := rows.Scan(&i.ProjectID, &i.AgentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProcessesForExecutionRevoked = `-- name: ListProcessesForExecutionRevoked :many
SELECT process.id, process.org_id, process.project_id, process.agent_id, process.tool_call_id, process.runtime_lock_id, process.agent_machine_binding_id, process.machine_id, process.execution_granted_at, process.io_mode, process.command, process.shell_selector, process.cwd, process.env, process.secret_env, process.timeout_seconds, process.initial_wait_ms, process.default_output_cursor, process.state, process.state_reason_code, process.state_reason_message, process.source_started_at, process.source_ended_at, process.state_changed_at, process.exit_code, process.exit_signal, process.created_at, process.updated_at, process.last_activity_at
FROM processes process
WHERE process.project_id = $1
  AND (
    process.state IN ('queued', 'starting', 'running')
    OR EXISTS (
      SELECT 1
      FROM process_actions action
      WHERE action.project_id = process.project_id
        AND action.agent_id = process.agent_id
        AND action.process_id = process.id
        AND action.state IN ('queued', 'accepted')
    )
  )
  AND (
    $2::uuid IS NOT NULL
    OR $3::uuid IS NOT NULL
    OR $4::uuid IS NOT NULL
  )
  AND (
    $2::uuid IS NULL
    OR process.agent_id = $2::uuid
  )
  AND (
    (
      $3::uuid IS NULL
      AND $4::uuid IS NULL
    )
    OR EXISTS (
      SELECT 1
      FROM project_machine_grants pmgrant
      WHERE pmgrant.project_id = process.project_id
        AND pmgrant.machine_id = process.machine_id
        AND (
          $3::uuid IS NULL
          OR pmgrant.id = $3::uuid
        )
        AND (
          $4::uuid IS NULL
          OR (
            pmgrant.source_kind = 'pool'
            AND pmgrant.project_machine_pool_grant_id = $4::uuid
          )
        )
    )
  )
ORDER BY process.project_id, process.agent_id, process.created_at, process.id
`

type ListProcessesForExecutionRevokedParams struct {
	ProjectID                 uuid.UUID
	AgentID                   *uuid.UUID
	ProjectMachineGrantID     *uuid.UUID
	ProjectMachinePoolGrantID *uuid.UUID
}

func (q *Queries) ListProcessesForExecutionRevoked(ctx context.Context, arg ListProcessesForExecutionRevokedParams) ([]Process, error) {
	rows, err := q.db.Query(ctx, listProcessesForExecutionRevoked,
		arg.ProjectID,
		arg.AgentID,
		arg.ProjectMachineGrantID,
		arg.ProjectMachinePoolGrantID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Process{}
	for rows.Next() {
		var i Process
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.AgentID,
			&i.ToolCallID,
			&i.RuntimeLockID,
			&i.AgentMachineBindingID,
			&i.MachineID,
			&i.ExecutionGrantedAt,
			&i.IoMode,
			&i.Command,
			&i.ShellSelector,
			&i.Cwd,
			&i.Env,
			&i.SecretEnv,
			&i.TimeoutSeconds,
			&i.InitialWaitMs,
			&i.DefaultOutputCursor,
			&i.State,
			&i.StateReasonCode,
			&i.StateReasonMessage,
			&i.SourceStartedAt,
			&i.SourceEndedAt,
			&i.StateChangedAt,
			&i.ExitCode,
			&i.ExitSignal,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProcessesForMachineLifecycleTermination = `-- name: ListProcessesForMachineLifecycleTermination :many
SELECT id, org_id, project_id, agent_id, tool_call_id, runtime_lock_id, agent_machine_binding_id, machine_id, execution_granted_at, io_mode, command, shell_selector, cwd, env, secret_env, timeout_seconds, initial_wait_ms, default_output_cursor, state, state_reason_code, state_reason_message, source_started_at, source_ended_at, state_changed_at, exit_code, exit_signal, created_at, updated_at, last_activity_at
FROM processes process
WHERE process.org_id = $1
  AND process.machine_id = $2
  AND (
    process.state IN ('starting', 'running')
    OR EXISTS (
      SELECT 1
      FROM process_actions action
      WHERE action.project_id = process.project_id
        AND action.agent_id = process.agent_id
        AND action.process_id = process.id
        AND action.state IN ('queued', 'accepted')
    )
  )
ORDER BY project_id, agent_id, created_at, id
`

type ListProcessesForMachineLifecycleTerminationParams struct {
	OrgID     uuid.UUID
	MachineID uuid.UUID
}

func (q *Queries) ListProcessesForMachineLifecycleTermination(ctx context.Context, arg ListProcessesForMachineLifecycleTerminationParams) ([]Process, error) {
	rows, err := q.db.Query(ctx, listProcessesForMachineLifecycleTermination, arg.OrgID, arg.MachineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Process{}
	for rows.Next() {
		var i Process
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.AgentID,
			&i.ToolCallID,
			&i.RuntimeLockID,
			&i.AgentMachineBindingID,
			&i.MachineID,
			&i.ExecutionGrantedAt,
			&i.IoMode,
			&i.Command,
			&i.ShellSelector,
			&i.Cwd,
			&i.Env,
			&i.SecretEnv,
			&i.TimeoutSeconds,
			&i.InitialWaitMs,
			&i.DefaultOutputCursor,
			&i.State,
			&i.StateReasonCode,
			&i.StateReasonMessage,
			&i.SourceStartedAt,
			&i.SourceEndedAt,
			&i.StateChangedAt,
			&i.ExitCode,
			&i.ExitSignal,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProcessesForMachineReconciliation = `-- name: ListProcessesForMachineReconciliation :many
SELECT process.id, process.org_id, process.project_id, process.agent_id, process.tool_call_id, process.runtime_lock_id, process.agent_machine_binding_id, process.machine_id, process.execution_granted_at, process.io_mode, process.command, process.shell_selector, process.cwd, process.env, process.secret_env, process.timeout_seconds, process.initial_wait_ms, process.default_output_cursor, process.state, process.state_reason_code, process.state_reason_message, process.source_started_at, process.source_ended_at, process.state_changed_at, process.exit_code, process.exit_signal, process.created_at, process.updated_at, process.last_activity_at
FROM processes process
WHERE process.org_id = $1
  AND process.machine_id = $2
  AND (
    process.state IN ('starting', 'running')
    OR EXISTS (
      SELECT 1
      FROM process_actions action
      WHERE action.project_id = process.project_id
        AND action.agent_id = process.agent_id
        AND action.process_id = process.id
        AND action.state IN ('queued', 'accepted')
    )
  )
`

type ListProcessesForMachineReconciliationParams struct {
	OrgID     uuid.UUID
	MachineID uuid.UUID
}

func (q *Queries) ListProcessesForMachineReconciliation(ctx context.Context, arg ListProcessesForMachineReconciliationParams) ([]Process, error) {
	rows, err := q.db.Query(ctx, listProcessesForMachineReconciliation, arg.OrgID, arg.MachineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Process{}
	for rows.Next() {
		var i Process
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.AgentID,
			&i.ToolCallID,
			&i.RuntimeLockID,
			&i.AgentMachineBindingID,
			&i.MachineID,
			&i.ExecutionGrantedAt,
			&i.IoMode,
			&i.Command,
			&i.ShellSelector,
			&i.Cwd,
			&i.Env,
			&i.SecretEnv,
			&i.TimeoutSeconds,
			&i.InitialWaitMs,
			&i.DefaultOutputCursor,
			&i.State,
			&i.StateReasonCode,
			&i.StateReasonMessage,
			&i.SourceStartedAt,
			&i.SourceEndedAt,
			&i.StateChangedAt,
			&i.ExitCode,
			&i.ExitSignal,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAgentsForExecutionRevoked = `-- name: LockAgentsForExecutionRevoked :many
SELECT agent.id
FROM agents agent
WHERE agent.project_id = $1
  AND (
    ($2::uuid IS NOT NULL AND agent.id = $2::uuid)
    OR (
      $2::uuid IS NULL
      AND ($3::uuid IS NOT NULL OR $4::uuid IS NOT NULL)
      AND EXISTS (
        SELECT 1
        FROM agent_machine_bindings binding
        JOIN project_machine_grants pmgrant ON pmgrant.project_id = binding.project_id
          AND pmgrant.machine_id = binding.machine_id
        WHERE binding.project_id = agent.project_id
          AND binding.agent_id = agent.id
          AND binding.state = 'attached'
          AND (
            $3::uuid IS NULL
            OR pmgrant.id = $3::uuid
          )
          AND (
            $4::uuid IS NULL
            OR (
              pmgrant.source_kind = 'pool'
              AND pmgrant.project_machine_pool_grant_id = $4::uuid
            )
          )
      )
    )
  )
ORDER BY agent.id
FOR UPDATE
`

type LockAgentsForExecutionRevokedParams struct {
	ProjectID                 uuid.UUID
	AgentID                   *uuid.UUID
	ProjectMachineGrantID     *uuid.UUID
	ProjectMachinePoolGrantID *uuid.UUID
}

func (q *Queries) LockAgentsForExecutionRevoked(ctx context.Context, arg LockAgentsForExecutionRevokedParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockAgentsForExecutionRevoked,
		arg.ProjectID,
		arg.AgentID,
		arg.ProjectMachineGrantID,
		arg.ProjectMachinePoolGrantID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDaemonProcessForAccept = `-- name: LockDaemonProcessForAccept :one
SELECT process.id
FROM processes process
WHERE process.org_id = $1
  AND process.machine_id = $2
  AND process.id = $3
FOR UPDATE
`

type LockDaemonProcessForAcceptParams struct {
	OrgID     uuid.UUID
	MachineID uuid.UUID
	ProcessID uuid.UUID
}

func (q *Queries) LockDaemonProcessForAccept(ctx context.Context, arg LockDaemonProcessForAcceptParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockDaemonProcessForAccept, arg.OrgID, arg.MachineID, arg.ProcessID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const lockProcessForActionCreation = `-- name: LockProcessForActionCreation :one
SELECT id
FROM processes
WHERE project_id = $1
  AND agent_id = $2
  AND id = $3
FOR UPDATE
`

type LockProcessForActionCreationParams struct {
	ProjectID uuid.UUID
	AgentID   uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) LockProcessForActionCreation(ctx context.Context, arg LockProcessForActionCreationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockProcessForActionCreation, arg.ProjectID, arg.AgentID, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const machineReachableForProjectMachine = `-- name: MachineReachableForProjectMachine :one
SELECT machine.id
FROM machines machine
JOIN project_machine_grants pmgrant ON pmgrant.org_id = machine.org_id
  AND pmgrant.machine_id = machine.id
  AND pmgrant.project_id = $1
JOIN machine_connection_states connection ON connection.org_id = machine.org_id
  AND connection.machine_id = machine.id
WHERE machine.id = $2
  AND machine.deleted_at IS NULL
  AND connection.connection_state IN ('online', 'asleep')
LIMIT 1
`

type MachineReachableForProjectMachineParams struct {
	ProjectID uuid.UUID
	MachineID uuid.UUID
}

func (q *Queries) MachineReachableForProjectMachine(ctx context.Context, arg MachineReachableForProjectMachineParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, machineReachableForProjectMachine, arg.ProjectID, arg.MachineID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const markActiveProcessUnknownByMachine = `-- name: MarkActiveProcessUnknownByMachine :one
UPDATE processes
SET state = 'unknown',
    state_reason_code = $1,
    state_reason_message = $2,
    state_changed_at = statement_timestamp(),
    last_activity_at = statement_timestamp(),
    updated_at = statement_timestamp()
WHERE org_id = $3
  AND machine_id = $4
  AND id = $5
  AND state IN ('starting', 'running')
RETURNING id, org_id, project_id, agent_id, tool_call_id, runtime_lock_id, agent_machine_binding_id, machine_id, execution_granted_at, io_mode, command, shell_selector, cwd, env, secret_env, timeout_seconds, initial_wait_ms, default_output_cursor, state, state_reason_code, state_reason_message, source_started_at, source_ended_at, state_changed_at, exit_code, exit_signal, created_at, updated_at, last_activity_at
`

type MarkActiveProcessUnknownByMachineParams struct {
	StateReasonCode    *string
	StateReasonMessage string
	OrgID              uuid.UUID
	MachineID          uuid.UUID
	ID                 uuid.UUID
}

func (q *Queries) MarkActiveProcessUnknownByMachine(ctx context.Context, arg MarkActiveProcessUnknownByMachineParams) (Process, error) {
	row := q.db.QueryRow(ctx, markActiveProcessUnknownByMachine,
		arg.StateReasonCode,
		arg.StateReasonMessage,
		arg.OrgID,
		arg.MachineID,
		arg.ID,
	)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.AgentID,
		&i.ToolCallID,
		&i.RuntimeLockID,
		&i.AgentMachineBindingID,
		&i.MachineID,
		&i.ExecutionGrantedAt,
		&i.IoMode,
		&i.Command,
		&i.ShellSelector,
		&i.Cwd,
		&i.Env,
		&i.SecretEnv,
		&i.TimeoutSeconds,
		&i.InitialWaitMs,
		&i.DefaultOutputCursor,
		&i.State,
		&i.StateReasonCode,
		&i.StateReasonMessage,
		&i.SourceStartedAt,
		&i.SourceEndedAt,
		&i.StateChangedAt,
		&i.ExitCode,
		&i.ExitSignal,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActivityAt,
	)
	return i, err
}

const markProcessStarted = `-- name: MarkProcessStarted :one
UPDATE processes process
SET state = 'running',
    source_started_at = coalesce(source_started_at, $1::timestamptz),
    state_changed_at = CASE
      WHEN state = 'starting' THEN statement_timestamp()
      ELSE state_changed_at
    END,
    updated_at = CASE
      WHEN state = 'starting' OR source_started_at IS NULL THEN statement_timestamp()
      ELSE updated_at
    END,
    last_activity_at = CASE
      WHEN state = 'starting' OR source_started_at IS NULL THEN statement_timestamp()
      ELSE last_activity_at
    END
WHERE process.project_id = $2
  AND process.agent_id = $3
  AND process.id = $4
  AND process.machine_id = $5
  AND process.state IN ('starting', 'running')
RETURNING process.id, process.org_id, process.project_id, process.agent_id, process.tool_call_id, process.runtime_lock_id, process.agent_machine_binding_id, process.machine_id, process.execution_granted_at, process.io_mode, process.command, process.shell_selector, process.cwd, process.env, process.secret_env, process.timeout_seconds, process.initial_wait_ms, process.default_output_cursor, process.state, process.state_reason_code, process.state_reason_message, process.source_started_at, process.source_ended_at, process.state_changed_at, process.exit_code, process.exit_signal, process.created_at, process.updated_at, process.last_activity_at
`

type MarkProcessStartedParams struct {
	SourceStartedAt time.Time
	ProjectID       uuid.UUID
	AgentID         uuid.UUID
	ID              uuid.UUID
	MachineID       uuid.UUID
}

func (q *Queries) MarkProcessStarted(ctx context.Context, arg MarkProcessStartedParams) (Process, error) {
	row := q.db.QueryRow(ctx, markProcessStarted,
		arg.SourceStartedAt,
		arg.ProjectID,
		arg.AgentID,
		arg.ID,
		arg.MachineID,
	)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.AgentID,
		&i.ToolCallID,
		&i.RuntimeLockID,
		&i.AgentMachineBindingID,
		&i.MachineID,
		&i.ExecutionGrantedAt,
		&i.IoMode,
		&i.Command,
		&i.ShellSelector,
		&i.Cwd,
		&i.Env,
		&i.SecretEnv,
		&i.TimeoutSeconds,
		&i.InitialWaitMs,
		&i.DefaultOutputCursor,
		&i.State,
		&i.StateReasonCode,
		&i.StateReasonMessage,
		&i.SourceStartedAt,
		&i.SourceEndedAt,
		&i.StateChangedAt,
		&i.ExitCode,
		&i.ExitSignal,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActivityAt,
	)
	return i, err
}
